import { useState } from 'react';
import { useArchitectureStore } from '../../entities/store/architectureStore';
import { useAuthStore } from '../../entities/store/authStore';
import { useUIStore } from '../../entities/store/uiStore';
import { apiPost, getApiErrorMessage, ApiError } from '../../shared/api/client';
import { isValidGitBranchName } from '../../shared/utils/githubValidation';
import { confirmDialog } from '../../shared/ui/ConfirmDialog';
import type { PullRequestResponse } from '../../shared/types/api';
import type { DiffDelta } from '../../shared/types/diff';
import './GitHubPR.css';

/** Build a Markdown summary from a DiffDelta for PR body prefill (#876) */
function buildDiffSummary(delta: DiffDelta): string {
  const lines: string[] = ['## Architecture Changes', ''];
  const { added, modified, removed } = ['plates', 'blocks', 'connections', 'externalActors'].reduce(
    (acc, key) => {
      const section = delta[key as keyof DiffDelta] as { added: { id: string }[]; modified: { id: string }[]; removed: { id: string }[] };
      return {
        added: acc.added + section.added.length,
        modified: acc.modified + section.modified.length,
        removed: acc.removed + section.removed.length,
      };
    },
    { added: 0, modified: 0, removed: 0 },
  );
  lines.push(`- **${added}** added, **${modified}** modified, **${removed}** removed`);
  if (delta.summary.hasBreakingChanges) {
    lines.push('- Breaking changes detected');
  }
  lines.push('', '_Generated by CloudBlocks_');
  return lines.join('\n');
}

export function GitHubPR() {
  const show = useUIStore((s) => s.showGitHubPR);
  const toggleGitHubPR = useUIStore((s) => s.toggleGitHubPR);
  const toggleGitHubLogin = useUIStore((s) => s.toggleGitHubLogin);
  const diffDelta = useUIStore((s) => s.diffDelta);
  const addActivity = useUIStore((s) => s.addActivity);

  const isAuthenticated = useAuthStore((s) => s.status) === 'authenticated';
  const authStatus = useAuthStore((s) => s.status);
  const user = useAuthStore((s) => s.user);
  const workspace = useArchitectureStore((s) => s.workspace);
  const hasBackendWorkspaceLink = Boolean(workspace.backendWorkspaceId);

  const baseBranch = 'main'; // inferred from workspace linkage
  const [title, setTitle] = useState('Update cloud architecture');
  const [body, setBody] = useState('');
  const [branch, setBranch] = useState('');
  const [commitMessage, setCommitMessage] = useState('Update architecture via CloudBlocks');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<PullRequestResponse | null>(null);
  const cleanedTitle = title.trim();
  const cleanedBranch = branch.trim();
  const cleanedCommitMessage = commitMessage.trim();
  const branchIsValid = !cleanedBranch || isValidGitBranchName(cleanedBranch);

  // #842: Block submission when head branch matches base branch
  const branchMatchesBase = cleanedBranch.length > 0 && cleanedBranch === baseBranch;
  const canSubmit = !loading && cleanedTitle.length > 0 && cleanedCommitMessage.length > 0 && branchIsValid && !branchMatchesBase && hasBackendWorkspaceLink;

  if (!show) return null;

  const isAuthError = (err: unknown): boolean =>
    err instanceof ApiError && (err.status === 401 || err.status === 403);

  // #857: Confirm before closing if form has edits
  const formIsDirty = title !== 'Update cloud architecture' || body.length > 0 || branch.length > 0 || commitMessage !== 'Update architecture via CloudBlocks';
  const handleClose = async () => {
    if (formIsDirty && !result) {
      const ok = await confirmDialog(
        'You have unsaved edits in the PR form. Closing will discard them.',
        'Discard PR Draft?',
      );
      if (!ok) return;
    }
    toggleGitHubPR();
  };

  // #876: Prefill body from active compare review
  const handlePrefillFromCompare = () => {
    if (diffDelta) {
      setBody(buildDiffSummary(diffDelta));
    }
  };

  const handleSubmit = async () => {
    const backendWorkspaceId = workspace.backendWorkspaceId;
    if (!backendWorkspaceId) {
      setError('Workspace must be linked to backend before creating a pull request.');
      return;
    }
    if (!cleanedTitle) {
      setError('Pull request title is required.');
      return;
    }
    if (cleanedBranch && !isValidGitBranchName(cleanedBranch)) {
      setError('Branch name contains invalid characters or format.');
      return;
    }
    // #842: base=head guard
    if (branchMatchesBase) {
      setError('Head branch cannot be the same as the base branch.');
      return;
    }
    if (!cleanedCommitMessage) {
      setError('Commit message is required.');
      return;
    }

    // #843: Preflight branch collision check
    // The backend handles actual branch creation, so we surface the error as an actionable message
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const response = await apiPost<PullRequestResponse>(
        `/api/v1/workspaces/${encodeURIComponent(backendWorkspaceId)}/pr`,
        {
          architecture: workspace.architecture,
          title: cleanedTitle,
          body,
          branch: cleanedBranch || undefined,
          commit_message: cleanedCommitMessage,
        }
      );
      setResult(response);
      addActivity('pr', `Created PR #${response.number}: ${cleanedTitle}`);
    } catch (err) {
      // #867: Route auth failures to login
      if (isAuthError(err)) {
        setError('Authentication expired. Please sign in again.');
        toggleGitHubPR();
        toggleGitHubLogin();
        return;
      }
      // #843: Surface branch collision as actionable error
      const msg = getApiErrorMessage(err, 'Failed to create pull request.');
      if (msg.toLowerCase().includes('branch') && (msg.toLowerCase().includes('exist') || msg.toLowerCase().includes('conflict'))) {
        setError(`Branch name collision: ${msg}. Please choose a different branch name.`);
      } else {
        setError(msg);
      }
      addActivity('pr-error', msg);
    } finally {
      setLoading(false);
    }
  };

  const repoUrl = workspace.githubRepo ? `https://github.com/${workspace.githubRepo}` : null;

  return (
    <div className="github-pr">
      <div className="github-pr-header">
        <h3 className="github-pr-title">Pull Request</h3>
        <button type="button" className="github-pr-close" onClick={() => void handleClose()} aria-label="Close pull request panel">
          ✕
        </button>
      </div>

      {authStatus === 'unknown' ? (
        <div className="github-pr-loading">Checking authentication...</div>
      ) : !isAuthenticated ? (
        <div className="github-pr-empty">GitHub authentication required.</div>
      ) : !hasBackendWorkspaceLink ? (
        <div className="github-pr-empty">Workspace must be linked to backend before creating a pull request.</div>
      ) : (
        <div className="github-pr-content">
          {/* Account context (#861) */}
          {user && (
            <div className="github-pr-account">
              Signed in as <strong>@{user.github_username ?? 'unknown'}</strong>
            </div>
          )}

          {/* Backend workspace ID (#844) and repo link (#862) */}
          <div className="github-pr-meta">
            {workspace.githubRepo && (
              <div className="github-pr-meta-row">
                Repo:{' '}
                {repoUrl ? (
                  <a className="github-pr-repo-link" href={repoUrl} target="_blank" rel="noopener noreferrer">
                    {workspace.githubRepo}
                  </a>
                ) : (
                  <span>{workspace.githubRepo}</span>
                )}
              </div>
            )}
            <div className="github-pr-meta-row">
              Backend ID: <code>{workspace.backendWorkspaceId}</code>
            </div>
          </div>

          {loading && <div className="github-pr-loading">Loading...</div>}
          {error && <div className="github-pr-error">{error}</div>}

          <label className="github-pr-label" htmlFor="github-pr-title">
            Title
          </label>
          <input
            id="github-pr-title"
            className="github-pr-input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />

          <label className="github-pr-label" htmlFor="github-pr-body">
            Body (optional)
            {diffDelta && (
              <button type="button" className="github-pr-prefill-btn" onClick={handlePrefillFromCompare}>
                Prefill from compare
              </button>
            )}
          </label>
          <textarea
            id="github-pr-body"
            className="github-pr-textarea"
            rows={5}
            value={body}
            onChange={(e) => setBody(e.target.value)}
          />

          <label className="github-pr-label" htmlFor="github-pr-branch">
            Branch name (optional)
          </label>
          <input
            id="github-pr-branch"
            className="github-pr-input"
            value={branch}
            onChange={(e) => setBranch(e.target.value)}
            placeholder="cloudblocks/update-architecture"
          />
          {!branchIsValid && <div className="github-pr-error">Branch name contains invalid characters or format.</div>}
          {branchMatchesBase && <div className="github-pr-error">Head branch cannot be the same as the base branch.</div>}

          <label className="github-pr-label" htmlFor="github-pr-commit-message">
            Commit message
          </label>
          <input
            id="github-pr-commit-message"
            className="github-pr-input"
            value={commitMessage}
            onChange={(e) => setCommitMessage(e.target.value)}
          />

          <button type="button" className="github-pr-submit" onClick={handleSubmit} disabled={!canSubmit}>
            Create Pull Request
          </button>

          {result && (
            <div className="github-pr-result">
              <div className="github-pr-result-info">
                PR #{result.number} · Branch: <code>{result.branch}</code>
              </div>
              <a className="github-pr-result-link" href={result.pull_request_url} target="_blank" rel="noreferrer">
                {result.pull_request_url}
              </a>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
