codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 80%

flags:
  web:
    paths:
      - apps/web/src/
    carryforward: true
  api:
    paths:
      - apps/api/app/
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
