import type { ArchitectureModel, Block, Connection } from '@cloudblocks/schema';
import { endpointId, generateEndpointsForBlock } from '@cloudblocks/schema';

const nodes: Block[] = [
  {
    id: 'vnet',
    name: 'Virtual Network',
    kind: 'container',
    layer: 'region',
    resourceType: 'virtual_network',
    category: 'network',
    provider: 'azure',
    parentId: null,
    position: { x: 0, y: 0, z: 0 },
    frame: { width: 34, depth: 24, height: 1 },
    metadata: {},
  },
  {
    id: 'subnet-a',
    name: 'App Subnet',
    kind: 'container',
    layer: 'subnet',
    resourceType: 'subnet',
    category: 'network',
    provider: 'azure',
    parentId: 'vnet',
    position: { x: -8, y: 0, z: 0 },
    frame: { width: 15, depth: 17, height: 0.6 },
    metadata: {},
  },
  {
    id: 'subnet-b',
    name: 'Data Subnet',
    kind: 'container',
    layer: 'subnet',
    resourceType: 'subnet',
    category: 'network',
    provider: 'azure',
    parentId: 'vnet',
    position: { x: 8, y: 0, z: 0 },
    frame: { width: 15, depth: 17, height: 0.6 },
    metadata: {},
  },
  {
    id: 'internet',
    name: 'Internet',
    kind: 'resource',
    layer: 'resource',
    resourceType: 'internet',
    category: 'delivery',
    provider: 'azure',
    roles: ['external'],
    parentId: null,
    position: { x: -28, y: 0, z: -5 },
    metadata: {},
  },
  {
    id: 'front-door',
    name: 'Front Door',
    kind: 'resource',
    layer: 'resource',
    resourceType: 'front_door',
    category: 'delivery',
    provider: 'azure',
    parentId: null,
    position: { x: -21, y: 0, z: -5 },
    metadata: {},
  },
  {
    id: 'gateway',
    name: 'App Gateway',
    kind: 'resource',
    layer: 'resource',
    resourceType: 'application_gateway',
    category: 'delivery',
    provider: 'azure',
    parentId: 'subnet-a',
    position: { x: -4, y: 0, z: -4 },
    metadata: {},
  },
  {
    id: 'app',
    name: 'App Service',
    kind: 'resource',
    layer: 'resource',
    resourceType: 'app_service',
    category: 'compute',
    provider: 'azure',
    parentId: null,
    position: { x: -21, y: 0, z: 3 },
    metadata: {},
  },
  {
    id: 'function',
    name: 'Functions',
    kind: 'resource',
    layer: 'resource',
    resourceType: 'function_compute',
    category: 'compute',
    provider: 'azure',
    parentId: null,
    position: { x: -28, y: 0, z: 3 },
    metadata: {},
  },
  {
    id: 'sql',
    name: 'SQL Database',
    kind: 'resource',
    layer: 'resource',
    resourceType: 'sql_database',
    category: 'data',
    provider: 'azure',
    parentId: null,
    position: { x: 22, y: 0, z: -5 },
    metadata: {},
  },
  {
    id: 'vault',
    name: 'Key Vault',
    kind: 'resource',
    layer: 'resource',
    resourceType: 'key_vault',
    category: 'security',
    provider: 'azure',
    parentId: null,
    position: { x: 22, y: 0, z: 3 },
    metadata: {},
  },
];

function link(id: string, from: string, to: string, semantic: 'http' | 'data'): Connection {
  return {
    id,
    from: endpointId(from, 'output', semantic),
    to: endpointId(to, 'input', semantic),
    metadata: {},
  };
}

export const spikeFixture: ArchitectureModel = {
  id: 'renderer-spike-web-api',
  name: 'Web API / Layer Study',
  version: '1',
  nodes,
  endpoints: nodes.flatMap((node) => generateEndpointsForBlock(node.id)),
  connections: [
    link('internet-front', 'internet', 'front-door', 'http'),
    link('front-gateway', 'front-door', 'gateway', 'http'),
    link('gateway-app', 'gateway', 'app', 'http'),
    link('app-sql', 'app', 'sql', 'data'),
    link('app-vault', 'app', 'vault', 'data'),
    link('function-sql', 'function', 'sql', 'data'),
  ],
  createdAt: '2026-09-23T00:00:00.000Z',
  updatedAt: '2026-09-23T00:00:00.000Z',
};
