import { describe, expect, it } from 'vitest';

import {
  normalizeBicep,
  generateMainBicep,
  generateParametersBicepparam,
  bicepPlugin,
} from './bicep';
import { azureProviderDefinition } from './provider';
import type { ArchitectureModel, ContainerNode, LeafNode } from '@cloudblocks/schema';
import type { GenerationOptions } from './types';
import {
  makeTestArchitecture,
  makeTestBlock,
  makeTestPlate,
  type LegacyArchitectureOverrides,
  type LegacyBlockOverrides,
  type LegacyPlateOverrides,
} from '../../__tests__/legacyModelTestUtils';

const basePosition = { x: 0, y: 0, z: 0 };
const baseSize = { width: 1, height: 1, depth: 1 };

function createPlate(overrides: LegacyPlateOverrides): ContainerNode {
  return makeTestPlate({
    id: 'plate-default',
    name: 'Default',
    type: 'region',
    parentId: null,
    position: basePosition,
    size: baseSize,
    metadata: {},
    ...overrides,
  });
}

function createBlock(overrides: LegacyBlockOverrides): LeafNode {
  return makeTestBlock({
    id: 'block-default',
    name: 'Default',
    category: 'compute',
    placementId: 'plate-default',
    position: basePosition,
    metadata: {},
    ...overrides,
  });
}

function createTestModel(overrides?: LegacyArchitectureOverrides): ArchitectureModel {
  return makeTestArchitecture({
    id: 'arch-1',
    name: 'Test',
    version: '1',
    plates: [],
    blocks: [],
    connections: [],
    externalActors: [
      { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: 5 } },
    ],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-01T00:00:00Z',
    ...overrides,
  });
}

const defaultOptions: GenerationOptions = {
  provider: 'azure',
  mode: 'draft',
  projectName: 'testproject',
  region: 'eastus',
};

describe('bicep generator', () => {
  it('bicepPlugin.id is bicep', () => {
    expect(bicepPlugin.id).toBe('bicep');
  });

  it('bicepPlugin.displayName is Bicep (Azure)', () => {
    expect(bicepPlugin.displayName).toBe('Bicep (Azure)');
  });

  it('bicepPlugin.supportedProviders is azure', () => {
    expect(bicepPlugin.supportedProviders).toEqual(['azure']);
  });

  it('filePlan returns main.bicep and parameters.bicepparam with bicep language', () => {
    const plan = bicepPlugin.filePlan?.(defaultOptions) ?? [];

    expect(plan).toEqual([
      { path: 'main.bicep', language: 'bicep' },
      { path: 'parameters.bicepparam', language: 'bicep' },
    ]);
  });

  it('normalizeBicep generates unique resource names', () => {
    const model = createTestModel({
      plates: [
        createPlate({ id: 'plate-network', name: 'VNet', type: 'region' }),
        createPlate({
          id: 'plate-subnet',
          name: 'Subnet 1',
          type: 'subnet',
          parentId: 'plate-network',
        }),
      ],
      blocks: [createBlock({ id: 'block-webapp', name: 'Frontend', category: 'compute' })],
    });

    const normalized = normalizeBicep(model, azureProviderDefinition);

    expect(normalized.resourceNames.get('plate-network')).toBe('vnetVnet');
    expect(normalized.resourceNames.get('plate-subnet')).toBe('subnetSubnet1');
    expect(normalized.resourceNames.get('block-webapp')).toBe('webappFrontend');
  });

  it('normalizeBicep handles duplicate names with numeric suffixes', () => {
    const model = createTestModel({
      blocks: [
        createBlock({ id: 'block-1', name: 'App', category: 'compute' }),
        createBlock({ id: 'block-2', name: 'App', category: 'compute' }),
      ],
    });

    const normalized = normalizeBicep(model, azureProviderDefinition);

    expect(normalized.resourceNames.get('block-1')).toBe('webappApp');
    expect(normalized.resourceNames.get('block-2')).toBe('webappApp2');
  });

  it('generateMainBicep contains header, params, and resource definitions', () => {
    const model = createTestModel({
      plates: [createPlate({ id: 'plate-network', name: 'Core', type: 'region' })],
      blocks: [createBlock({ id: 'block-web', name: 'Frontend', category: 'compute' })],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain('// Generated by CloudBlocks');
    expect(mainBicep).toContain("param projectName string = 'testproject'");
    expect(mainBicep).toContain("param location string = 'eastus'");
    expect(mainBicep).toContain(
      "resource vnetCore 'Microsoft.Network/virtualNetworks@2023-05-01' = {",
    );
    expect(mainBicep).toContain("resource webappFrontend 'Microsoft.Web/sites@2023-01-01' = {");
  });

  it('generateMainBicep includes service plan when compute blocks exist', () => {
    const model = createTestModel({
      blocks: [createBlock({ id: 'block-web', name: 'Frontend', category: 'compute' })],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain("resource servicePlan 'Microsoft.Web/serverfarms@2023-01-01' = {");
  });

  it('generateMainBicep includes service plan when only function blocks exist', () => {
    const model = createTestModel({
      blocks: [createBlock({ id: 'block-func', name: 'Fn', category: 'compute' })],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain("resource servicePlan 'Microsoft.Web/serverfarms@2023-01-01' = {");
  });

  it('generateMainBicep includes db params when database blocks exist', () => {
    const model = createTestModel({
      blocks: [createBlock({ id: 'block-db', name: 'MainDb', category: 'data' })],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain("param dbAdminUsername string = 'pgadmin'");
    expect(mainBicep).toContain('@secure()');
    expect(mainBicep).toContain('param dbAdminPassword string');
  });

  it('generateMainBicep generates all block categories', () => {
    const model = createTestModel({
      blocks: [
        createBlock({ id: 'block-compute', name: 'Compute', category: 'compute' }),
        createBlock({ id: 'block-database', name: 'Database', category: 'data' }),
        createBlock({ id: 'block-storage', name: 'Storage', category: 'data' }),
        createBlock({ id: 'block-gateway', name: 'Gateway', category: 'edge' }),
        createBlock({ id: 'block-function', name: 'Function', category: 'compute' }),
        createBlock({ id: 'block-queue', name: 'Queue', category: 'messaging' }),
        createBlock({ id: 'block-event', name: 'Event', category: 'messaging' }),
        createBlock({ id: 'block-analytics', name: 'Analytics', category: 'operations' }),
        createBlock({ id: 'block-identity', name: 'Identity', category: 'security' }),
        createBlock({ id: 'block-observability', name: 'Observability', category: 'operations' }),
      ],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain("resource webappCompute 'Microsoft.Web/sites@2023-01-01' = {");
    expect(mainBicep).toContain(
      "resource pgserverDatabase 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' = {",
    );
    expect(mainBicep).toContain(
      "resource pgserverStorage 'Microsoft.DBforPostgreSQL/flexibleServers@2023-03-01-preview' = {",
    );
    expect(mainBicep).toContain(
      "resource appgwGateway 'Microsoft.Network/applicationGateways@2023-05-01' = {",
    );
    expect(mainBicep).toContain("resource webappFunction 'Microsoft.Web/sites@2023-01-01' = {");
    expect(mainBicep).toContain(
      "resource queueQueue 'Microsoft.Storage/storageAccounts/queueServices/queues@2023-01-01' = {",
    );
    expect(mainBicep).toContain(
      "resource queueEvent 'Microsoft.Storage/storageAccounts/queueServices/queues@2023-01-01' = {",
    );
    expect(mainBicep).toContain(
      "resource analyticsAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {",
    );
    expect(mainBicep).toContain(
      "resource identityIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {",
    );
    expect(mainBicep).toContain(
      "resource analyticsObservability 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {",
    );
  });

  it('generates subnet as top-level resource when parent is missing', () => {
    const model = createTestModel({
      plates: [
        createPlate({
          id: 'sub-orphan',
          name: 'Orphan Subnet',
          type: 'subnet',
          parentId: 'missing-network',
        }),
      ],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain(
      "resource subnetOrphansubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' = {",
    );
    expect(mainBicep).toContain('location: location');
    expect(mainBicep).not.toContain('parent: ');
  });

  it('generateParametersBicepparam contains projectName and location values', () => {
    const params = generateParametersBicepparam(defaultOptions);

    expect(params).toContain("param projectName = 'testproject'");
    expect(params).toContain("param location = 'eastus'");
  });

  it('bicepPlugin.generate returns expected metadata', () => {
    const model = createTestModel({
      blocks: [createBlock({ id: 'block-web', name: 'Frontend', category: 'compute' })],
    });
    const normalized = bicepPlugin.normalize(model, {
      provider: azureProviderDefinition,
      mode: 'draft',
    });
    const output = bicepPlugin.generate(normalized, {
      provider: azureProviderDefinition,
      mode: 'draft',
      options: defaultOptions,
    });

    expect(output.files).toEqual([
      expect.objectContaining({ path: 'main.bicep', language: 'bicep' }),
      expect.objectContaining({ path: 'parameters.bicepparam', language: 'bicep' }),
    ]);
    expect(output.metadata.generator).toBe('bicep');
    expect(output.metadata.version).toBe('1.0.0');
    expect(output.metadata.provider).toBe('azure');
    expect(output.metadata.generatedAt).toEqual(expect.any(String));
  });

  it('generates implicit PIP + NIC for VM blocks', () => {
    const model = createTestModel({
      blocks: [createBlock({ id: 'vm1', name: 'WebServer', category: 'compute', subtype: 'vm' })],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain(
      "resource vmWebserverPip 'Microsoft.Network/publicIPAddresses@2023-05-01' = {",
    );
    expect(mainBicep).toContain("publicIPAllocationMethod: 'Static'");
    expect(mainBicep).toContain(
      "resource vmWebserverNic 'Microsoft.Network/networkInterfaces@2023-05-01' = {",
    );
    expect(mainBicep).toContain('id: vmWebserverPip.id');

    const pipIndex = mainBicep.indexOf('publicIPAddresses');
    const nicIndex = mainBicep.indexOf('networkInterfaces');
    expect(pipIndex).toBeLessThan(nicIndex);
  });

  it('generates implicit PIP for firewall blocks but no NIC', () => {
    const model = createTestModel({
      blocks: [
        createBlock({ id: 'fw1', name: 'MainFirewall', category: 'edge', subtype: 'firewall' }),
      ],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).toContain(
      "resource appgwMainfirewallPip 'Microsoft.Network/publicIPAddresses@2023-05-01' = {",
    );
    expect(mainBicep).not.toContain('networkInterfaces');
  });

  it('does not generate implicit resources for internal-lb blocks', () => {
    const model = createTestModel({
      blocks: [
        createBlock({ id: 'lb1', name: 'InternalLB', category: 'edge', subtype: 'internal-lb' }),
      ],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).not.toContain('publicIPAddresses');
    expect(mainBicep).not.toContain('networkInterfaces');
  });

  it('does not generate implicit resources for regular compute blocks without subtype', () => {
    const model = createTestModel({
      blocks: [createBlock({ id: 'web1', name: 'App', category: 'compute' })],
    });
    const normalized = normalizeBicep(model, azureProviderDefinition);
    const mainBicep = generateMainBicep(normalized, azureProviderDefinition, defaultOptions);

    expect(mainBicep).not.toContain('publicIPAddresses');
    expect(mainBicep).not.toContain('networkInterfaces');
  });
});
