import type { ArchitectureTemplate } from '../../shared/types/template';
import type { ContainerCapableResourceType, ContainerLayer } from '@cloudblocks/schema';
import { endpointId } from '@cloudblocks/schema';
import { registerTemplate } from './registry';

const CONTAINER_RESOURCE_TYPE: Record<ContainerLayer, ContainerCapableResourceType> = {
  global: 'virtual_network',
  edge: 'virtual_network',
  region: 'virtual_network',
  zone: 'virtual_network',
  subnet: 'subnet',
};

/**
 * External actor positions for templates with VNet width=36 CU (T1, T3, T4).
 * x range -18..+18, so external actors sit at x=-24 (outside the VNet).
 * Templates with different VNet sizes define their own constants below.
 */
const EXT_CLIENT_POS = { x: -24, y: 0, z: -4 } as const;
const EXT_INTERNET_POS = { x: -24, y: 0, z: 4 } as const;

/** External actor positions for Simple Compute (VNet width=30, x range -15..+15). */
const T2_EXT_CLIENT_POS = { x: -21, y: 0, z: -3 } as const;
const T2_EXT_INTERNET_POS = { x: -21, y: 0, z: 3 } as const;

/** External actor positions for Full-Stack Serverless (VNet width=48, x range -24..+24). */
const T6_EXT_CLIENT_POS = { x: -31, y: 0, z: -8 } as const;
const T6_EXT_INTERNET_POS = { x: -31, y: 0, z: 0 } as const;

/**
 * Built-in Templates (v0.4 + v1.0)
 * Based on docs/engine/templates.md
 *
 * v0.4 templates use compute, database, storage, gateway blocks.
 * v1.0 templates add serverless blocks: function, queue, and event.
 */

const threeTierTemplate: ArchitectureTemplate = {
  id: 'template-three-tier',
  name: 'Three-Tier Web Application',
  description:
    'Classic three-tier architecture with gateway, compute, database, and storage. ' +
    'Internet traffic enters through the Application Gateway in the Ingress Subnet, ' +
    'routes to a Compute instance in the App Subnet, then connects to Database and Storage in the Data Subnet. ' +
    'In production Azure deployments, Application Gateway uses a dedicated subnet.',
  category: 'web-application',
  difficulty: 'beginner',
  tags: ['three-tier', 'web', 'gateway', 'database', 'beginner'],
  architecture: {
    name: 'Three-Tier Web App',
    version: '1',
    endpoints: [],
    nodes: [
      {
        id: 'container-tmpl-vnet',
        name: 'VNet',
        kind: 'container',
        layer: 'region',
        resourceType: CONTAINER_RESOURCE_TYPE.region,
        category: 'network',
        provider: 'azure',
        parentId: null,
        position: { x: 0, y: 0, z: 0 },
        frame: { width: 36, height: 1.0, depth: 30 },
        metadata: {},
      },
      {
        id: 'container-tmpl-public',
        name: 'Ingress Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet',
        position: { x: -7, y: 0.3, z: -6 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-app',
        name: 'App Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet',
        position: { x: 7, y: 0.3, z: -6 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-private',
        name: 'Data Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet',
        position: { x: 0, y: 0.3, z: 6 },
        frame: { width: 15, height: 0.6, depth: 9 },
        metadata: {},
      },
      {
        id: 'block-tmpl-gw',
        name: 'Azure Application Gateway',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'application-gateway',
        category: 'delivery',
        provider: 'azure',
        subtype: 'application-gateway',
        parentId: 'container-tmpl-public',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-compute',
        name: 'Azure VM',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'vm',
        category: 'compute',
        provider: 'azure',
        subtype: 'vm',
        parentId: 'container-tmpl-app',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-db',
        name: 'Azure Database for PostgreSQL',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'azure-postgresql',
        category: 'data',
        provider: 'azure',
        subtype: 'azure-postgresql',
        parentId: 'container-tmpl-private',
        position: { x: -3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-storage',
        name: 'Azure Blob Storage',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'blob-storage',
        category: 'data',
        provider: 'azure',
        subtype: 'blob-storage',
        parentId: 'container-tmpl-private',
        position: { x: 3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'ext-browser',
        name: 'Client',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'browser',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...EXT_CLIENT_POS },
        metadata: {},
      },
      {
        id: 'ext-internet',
        name: 'Internet',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'internet',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...EXT_INTERNET_POS },
        metadata: {},
      },
    ],
    connections: [
      {
        id: 'conn-browser-internet',
        from: endpointId('ext-browser', 'output', 'http'),
        to: endpointId('ext-internet', 'input', 'http'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-inet-gw',
        from: endpointId('ext-internet', 'output', 'data'),
        to: endpointId('block-tmpl-gw', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-gw-compute',
        from: endpointId('block-tmpl-gw', 'output', 'data'),
        to: endpointId('block-tmpl-compute', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-compute-db',
        from: endpointId('block-tmpl-compute', 'output', 'data'),
        to: endpointId('block-tmpl-db', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-compute-storage',
        from: endpointId('block-tmpl-compute', 'output', 'data'),
        to: endpointId('block-tmpl-storage', 'input', 'data'),
        metadata: {},
      },
    ],
    externalActors: [
      { id: 'ext-browser', name: 'Client', type: 'browser', position: { ...EXT_CLIENT_POS } },
      { id: 'ext-internet', name: 'Internet', type: 'internet', position: { ...EXT_INTERNET_POS } },
    ],
  },
};

const simpleComputeTemplate: ArchitectureTemplate = {
  id: 'template-simple-compute',
  name: 'Simple Compute Setup',
  description:
    'Minimal architecture with dedicated ingress and app subnets. ' +
    'Internet traffic enters Application Gateway in the Ingress Subnet and reaches an Azure VM in the App Subnet.',
  category: 'web-application',
  difficulty: 'beginner',
  tags: ['simple', 'compute', 'minimal', 'beginner'],
  architecture: {
    name: 'Simple Compute',
    version: '1',
    endpoints: [],
    nodes: [
      {
        id: 'container-tmpl-vnet2',
        name: 'VNet',
        kind: 'container',
        layer: 'region',
        resourceType: CONTAINER_RESOURCE_TYPE.region,
        category: 'network',
        provider: 'azure',
        parentId: null,
        position: { x: 0, y: 0, z: 0 },
        frame: { width: 30, height: 1.0, depth: 18 },
        metadata: {},
      },
      {
        id: 'container-tmpl-pub2',
        name: 'Ingress Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet2',
        position: { x: -6, y: 0.3, z: 0 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-app2',
        name: 'App Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet2',
        position: { x: 6, y: 0.3, z: 0 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'block-tmpl-gw2',
        name: 'Azure Application Gateway',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'application-gateway',
        category: 'delivery',
        provider: 'azure',
        subtype: 'application-gateway',
        parentId: 'container-tmpl-pub2',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-compute2',
        name: 'Azure VM',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'vm',
        category: 'compute',
        provider: 'azure',
        subtype: 'vm',
        parentId: 'container-tmpl-app2',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'ext-browser',
        name: 'Client',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'browser',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...T2_EXT_CLIENT_POS },
        metadata: {},
      },
      {
        id: 'ext-internet',
        name: 'Internet',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'internet',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...T2_EXT_INTERNET_POS },
        metadata: {},
      },
    ],
    connections: [
      {
        id: 'conn-browser-internet',
        from: endpointId('ext-browser', 'output', 'http'),
        to: endpointId('ext-internet', 'input', 'http'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-inet-gw2',
        from: endpointId('ext-internet', 'output', 'data'),
        to: endpointId('block-tmpl-gw2', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-gw-app2',
        from: endpointId('block-tmpl-gw2', 'output', 'data'),
        to: endpointId('block-tmpl-compute2', 'input', 'data'),
        metadata: {},
      },
    ],
    externalActors: [
      { id: 'ext-browser', name: 'Client', type: 'browser', position: { ...T2_EXT_CLIENT_POS } },
      {
        id: 'ext-internet',
        name: 'Internet',
        type: 'internet',
        position: { ...T2_EXT_INTERNET_POS },
      },
    ],
  },
};

const dataStorageTemplate: ArchitectureTemplate = {
  id: 'template-data-storage',
  name: 'Data Storage Backend',
  description:
    'Backend architecture focused on data storage. Compute connects to both a database ' +
    'and blob storage in a dedicated subnet for secure data handling.',
  category: 'data-pipeline',
  difficulty: 'intermediate',
  tags: ['data', 'storage', 'database', 'private', 'intermediate'],
  architecture: {
    name: 'Data Storage Backend',
    version: '1',
    endpoints: [],
    nodes: [
      {
        id: 'container-tmpl-vnet3',
        name: 'VNet',
        kind: 'container',
        layer: 'region',
        resourceType: CONTAINER_RESOURCE_TYPE.region,
        category: 'network',
        provider: 'azure',
        parentId: null,
        position: { x: 0, y: 0, z: 0 },
        frame: { width: 36, height: 1.0, depth: 30 },
        metadata: {},
      },
      {
        id: 'container-tmpl-pub3',
        name: 'Ingress Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet3',
        position: { x: -7, y: 0.3, z: -6 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-app3',
        name: 'App Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet3',
        position: { x: 7, y: 0.3, z: -6 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-priv3',
        name: 'Data Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet3',
        position: { x: 0, y: 0.3, z: 6 },
        frame: { width: 15, height: 0.6, depth: 9 },
        metadata: {},
      },
      {
        id: 'block-tmpl-gw3',
        name: 'Azure Application Gateway',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'application-gateway',
        category: 'delivery',
        provider: 'azure',
        subtype: 'application-gateway',
        parentId: 'container-tmpl-pub3',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-api3',
        name: 'Azure VM',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'vm',
        category: 'compute',
        provider: 'azure',
        subtype: 'vm',
        parentId: 'container-tmpl-app3',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-db3',
        name: 'Azure SQL Database',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'sql-database',
        category: 'data',
        provider: 'azure',
        subtype: 'sql-database',
        parentId: 'container-tmpl-priv3',
        position: { x: -3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-blob3',
        name: 'Azure Blob Storage',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'blob-storage',
        category: 'data',
        provider: 'azure',
        subtype: 'blob-storage',
        parentId: 'container-tmpl-priv3',
        position: { x: 3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'ext-browser',
        name: 'Client',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'browser',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...EXT_CLIENT_POS },
        metadata: {},
      },
      {
        id: 'ext-internet',
        name: 'Internet',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'internet',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...EXT_INTERNET_POS },
        metadata: {},
      },
    ],
    connections: [
      {
        id: 'conn-browser-internet',
        from: endpointId('ext-browser', 'output', 'http'),
        to: endpointId('ext-internet', 'input', 'http'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-inet-gw3',
        from: endpointId('ext-internet', 'output', 'data'),
        to: endpointId('block-tmpl-gw3', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-gw-api3',
        from: endpointId('block-tmpl-gw3', 'output', 'data'),
        to: endpointId('block-tmpl-api3', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-api-db3',
        from: endpointId('block-tmpl-api3', 'output', 'data'),
        to: endpointId('block-tmpl-db3', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-api-blob3',
        from: endpointId('block-tmpl-api3', 'output', 'data'),
        to: endpointId('block-tmpl-blob3', 'input', 'data'),
        metadata: {},
      },
    ],
    externalActors: [
      { id: 'ext-browser', name: 'Client', type: 'browser', position: { ...EXT_CLIENT_POS } },
      { id: 'ext-internet', name: 'Internet', type: 'internet', position: { ...EXT_INTERNET_POS } },
    ],
  },
};

// ─── v1.0 Serverless Templates ──────────────────────────────

const serverlessHttpApiTemplate: ArchitectureTemplate = {
  id: 'template-serverless-http-api',
  name: 'Serverless HTTP API',
  description:
    'Serverless architecture for HTTP APIs. Internet traffic enters via Gateway, ' +
    'triggers a Function, which reads/writes to Storage and Database. ' +
    'No VMs — fully managed serverless compute.',
  category: 'serverless',
  difficulty: 'intermediate',
  tags: ['serverless', 'function', 'http', 'api', 'gateway'],
  generatorCompat: ['terraform', 'bicep', 'pulumi'],
  architecture: {
    name: 'Serverless HTTP API',
    version: '1',
    endpoints: [],
    nodes: [
      {
        id: 'container-tmpl-vnet4',
        name: 'VNet',
        kind: 'container',
        layer: 'region',
        resourceType: CONTAINER_RESOURCE_TYPE.region,
        category: 'network',
        provider: 'azure',
        parentId: null,
        position: { x: 0, y: 0, z: 0 },
        frame: { width: 36, height: 1.0, depth: 30 },
        metadata: {},
      },
      {
        id: 'container-tmpl-pub4',
        name: 'APIM Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet4',
        position: { x: -7, y: 0.3, z: -6 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-int4',
        name: 'Integration Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet4',
        position: { x: 7, y: 0.3, z: -6 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-priv4',
        name: 'Data Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet4',
        position: { x: 0, y: 0.3, z: 6 },
        frame: { width: 15, height: 0.6, depth: 9 },
        metadata: {},
      },
      {
        id: 'block-tmpl-gw4',
        name: 'Azure API Management',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'api-management',
        category: 'delivery',
        provider: 'azure',
        subtype: 'api-management',
        parentId: 'container-tmpl-pub4',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-func4',
        name: 'Azure Functions',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'functions',
        category: 'compute',
        provider: 'azure',
        subtype: 'functions',
        parentId: 'container-tmpl-int4',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-storage4',
        name: 'Azure Blob Storage',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'blob-storage',
        category: 'data',
        provider: 'azure',
        subtype: 'blob-storage',
        parentId: 'container-tmpl-priv4',
        position: { x: -3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-db4',
        name: 'Azure Cosmos DB',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'cosmos-db',
        category: 'data',
        provider: 'azure',
        subtype: 'cosmos-db',
        parentId: 'container-tmpl-priv4',
        position: { x: 3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'ext-browser',
        name: 'Client',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'browser',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...EXT_CLIENT_POS },
        metadata: {},
      },
      {
        id: 'ext-internet',
        name: 'Internet',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'internet',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...EXT_INTERNET_POS },
        metadata: {},
      },
    ],
    connections: [
      {
        id: 'conn-browser-internet',
        from: endpointId('ext-browser', 'output', 'http'),
        to: endpointId('ext-internet', 'input', 'http'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-inet-gw4',
        from: endpointId('ext-internet', 'output', 'data'),
        to: endpointId('block-tmpl-gw4', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-gw-func4',
        from: endpointId('block-tmpl-gw4', 'output', 'data'),
        to: endpointId('block-tmpl-func4', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-func-storage4',
        from: endpointId('block-tmpl-func4', 'output', 'data'),
        to: endpointId('block-tmpl-storage4', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-func-db4',
        from: endpointId('block-tmpl-func4', 'output', 'data'),
        to: endpointId('block-tmpl-db4', 'input', 'data'),
        metadata: {},
      },
    ],
    externalActors: [
      { id: 'ext-browser', name: 'Client', type: 'browser', position: { ...EXT_CLIENT_POS } },
      { id: 'ext-internet', name: 'Internet', type: 'internet', position: { ...EXT_INTERNET_POS } },
    ],
  },
};

const eventDrivenPipelineTemplate: ArchitectureTemplate = {
  id: 'template-event-driven-pipeline',
  name: 'Event-Driven Pipeline',
  description:
    'Event-driven data processing pipeline. Events trigger a processing function ' +
    'that reads from a queue and writes results to storage. A timer trigger block represents a ' +
    'scheduled invocation configuration on the Function, visualized as a separate trigger source.',
  category: 'data-pipeline',
  difficulty: 'advanced',
  tags: ['event-driven', 'queue', 'function', 'event', 'pipeline'],
  generatorCompat: ['terraform', 'bicep', 'pulumi'],
  architecture: {
    name: 'Event-Driven Pipeline',
    version: '1',
    endpoints: [],
    nodes: [
      {
        id: 'container-tmpl-vnet5',
        name: 'VNet',
        kind: 'container',
        layer: 'region',
        resourceType: CONTAINER_RESOURCE_TYPE.region,
        category: 'network',
        provider: 'azure',
        parentId: null,
        position: { x: 0, y: 0, z: 0 },
        frame: { width: 36, height: 1.0, depth: 28 },
        metadata: {},
      },
      {
        id: 'container-tmpl-comp5',
        name: 'Functions Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet5',
        position: { x: -8, y: 0.3, z: 6 },
        frame: { width: 12, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-tmpl-priv5',
        name: 'Data Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-tmpl-vnet5',
        position: { x: 9, y: 0.3, z: 6 },
        frame: { width: 9, height: 0.6, depth: 9 },
        metadata: {},
      },
      {
        id: 'block-tmpl-event5',
        name: 'Azure Event Grid',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'event-grid',
        category: 'messaging',
        provider: 'azure',
        subtype: 'event-grid',
        parentId: 'container-tmpl-vnet5',
        position: { x: -5, y: 0.5, z: -6 },
        metadata: {},
      },
      {
        id: 'block-tmpl-queue5',
        name: 'Azure Service Bus',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'service-bus',
        category: 'messaging',
        provider: 'azure',
        subtype: 'service-bus',
        parentId: 'container-tmpl-vnet5',
        position: { x: 0, y: 0.5, z: -6 },
        metadata: {},
      },
      {
        id: 'block-tmpl-timer5',
        name: 'Azure Functions Timer Trigger',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'timer-trigger',
        category: 'messaging',
        provider: 'azure',
        subtype: 'timer-trigger',
        parentId: 'container-tmpl-vnet5',
        position: { x: 5, y: 0.5, z: -6 },
        metadata: {},
      },
      {
        id: 'block-tmpl-func5a',
        name: 'Azure Functions',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'functions',
        category: 'compute',
        provider: 'azure',
        subtype: 'functions',
        parentId: 'container-tmpl-comp5',
        position: { x: -2, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-func5b',
        name: 'Azure Functions (Batch)',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'functions',
        category: 'compute',
        provider: 'azure',
        subtype: 'functions',
        parentId: 'container-tmpl-comp5',
        position: { x: 2, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-tmpl-storage5',
        name: 'Azure Blob Storage',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'blob-storage',
        category: 'data',
        provider: 'azure',
        subtype: 'blob-storage',
        parentId: 'container-tmpl-priv5',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
    ],
    connections: [
      {
        id: 'conn-tmpl-event-func5a',
        from: endpointId('block-tmpl-event5', 'output', 'data'),
        to: endpointId('block-tmpl-func5a', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-queue-func5a',
        from: endpointId('block-tmpl-queue5', 'output', 'data'),
        to: endpointId('block-tmpl-func5a', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-func5a-storage',
        from: endpointId('block-tmpl-func5a', 'output', 'data'),
        to: endpointId('block-tmpl-storage5', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-func5a-queue',
        from: endpointId('block-tmpl-func5a', 'output', 'data'),
        to: endpointId('block-tmpl-queue5', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-timer-func5b',
        from: endpointId('block-tmpl-timer5', 'output', 'data'),
        to: endpointId('block-tmpl-func5b', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-tmpl-func5b-storage',
        from: endpointId('block-tmpl-func5b', 'output', 'data'),
        to: endpointId('block-tmpl-storage5', 'input', 'data'),
        metadata: {},
      },
    ],
    externalActors: [],
  },
};

const fullStackServerlessTemplate: ArchitectureTemplate = {
  id: 'template-full-stack-serverless',
  name: 'Full-Stack Web App with Event Processing',
  description:
    'Maximum-complexity architecture using all block types. Internet traffic enters via Gateway ' +
    'to a Compute frontend and API Management, then to a serverless API Function. Events, Queues, and Timers drive ' +
    'background processing Functions. Data flows to Database and Storage in the Data Subnet. ' +
    'Uses 8 of 10 block categories, dedicated ingress/app/integration/data subnets, and 12 connections.',
  category: 'serverless',
  difficulty: 'advanced',
  tags: [
    'full-stack',
    'serverless',
    'event-driven',
    'queue',
    'event',
    'function',
    'compute',
    'gateway',
    'database',
    'storage',
    'advanced',
  ],
  generatorCompat: ['terraform', 'bicep', 'pulumi'],
  architecture: {
    name: 'Full-Stack Web App',
    version: '1',
    endpoints: [],
    nodes: [
      {
        id: 'container-fs-vnet',
        name: 'VNet',
        kind: 'container',
        layer: 'region',
        resourceType: CONTAINER_RESOURCE_TYPE.region,
        category: 'network',
        provider: 'azure',
        parentId: null,
        position: { x: 0, y: 0, z: 0 },
        frame: { width: 48, height: 1.0, depth: 42 },
        metadata: {},
      },
      {
        id: 'container-fs-agw',
        name: 'App Gateway Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-fs-vnet',
        position: { x: -14, y: 0.3, z: -11 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-fs-apim-subnet',
        name: 'APIM Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-fs-vnet',
        position: { x: -4, y: 0.3, z: -11 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-fs-app',
        name: 'App Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-fs-vnet',
        position: { x: -14, y: 0.3, z: 0 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-fs-api-subnet',
        name: 'API Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-fs-vnet',
        position: { x: -4, y: 0.3, z: 0 },
        frame: { width: 8, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-fs-integration',
        name: 'Processing Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-fs-vnet',
        position: { x: -12, y: 0.3, z: 11 },
        frame: { width: 12, height: 0.6, depth: 8 },
        metadata: {},
      },
      {
        id: 'container-fs-private',
        name: 'Data Subnet',
        kind: 'container',
        layer: 'subnet',
        resourceType: CONTAINER_RESOURCE_TYPE.subnet,
        category: 'network',
        provider: 'azure',
        parentId: 'container-fs-vnet',
        position: { x: 8, y: 0.3, z: 11 },
        frame: { width: 15, height: 0.6, depth: 9 },
        metadata: {},
      },

      // Subnet 1
      {
        id: 'block-fs-gw',
        name: 'Azure Application Gateway',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'application-gateway',
        category: 'delivery',
        provider: 'azure',
        subtype: 'application-gateway',
        parentId: 'container-fs-agw',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-fs-apim',
        name: 'Azure API Management',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'api-management',
        category: 'delivery',
        provider: 'azure',
        subtype: 'api-management',
        parentId: 'container-fs-apim-subnet',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-fs-web',
        name: 'Azure VM',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'vm',
        category: 'compute',
        provider: 'azure',
        subtype: 'vm',
        parentId: 'container-fs-app',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      // Subnet 2
      {
        id: 'block-fs-db',
        name: 'Azure Database for PostgreSQL',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'azure-postgresql',
        category: 'data',
        provider: 'azure',
        subtype: 'azure-postgresql',
        parentId: 'container-fs-private',
        position: { x: -3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-fs-storage',
        name: 'Azure Blob Storage',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'blob-storage',
        category: 'data',
        provider: 'azure',
        subtype: 'blob-storage',
        parentId: 'container-fs-private',
        position: { x: 3, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-fs-api',
        name: 'Azure Functions',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'functions',
        category: 'compute',
        provider: 'azure',
        subtype: 'functions',
        parentId: 'container-fs-api-subnet',
        position: { x: 0, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-fs-worker',
        name: 'Azure Functions (Worker)',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'functions',
        category: 'compute',
        provider: 'azure',
        subtype: 'functions',
        parentId: 'container-fs-integration',
        position: { x: -2, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-fs-batch',
        name: 'Azure Functions (Batch)',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'functions',
        category: 'compute',
        provider: 'azure',
        subtype: 'functions',
        parentId: 'container-fs-integration',
        position: { x: 2, y: 0.5, z: 0 },
        metadata: {},
      },
      {
        id: 'block-fs-queue',
        name: 'Azure Service Bus',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'service-bus',
        category: 'messaging',
        provider: 'azure',
        subtype: 'service-bus',
        parentId: 'container-fs-vnet',
        position: { x: 18, y: 0.5, z: -11 },
        metadata: {},
      },
      {
        id: 'block-fs-event',
        name: 'Azure Event Grid',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'event-grid',
        category: 'messaging',
        provider: 'azure',
        subtype: 'event-grid',
        parentId: 'container-fs-vnet',
        position: { x: 18, y: 0.5, z: -5 },
        metadata: {},
      },
      {
        id: 'block-fs-timer',
        name: 'Azure Functions Timer Trigger',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'timer-trigger',
        category: 'messaging',
        provider: 'azure',
        subtype: 'timer-trigger',
        parentId: 'container-fs-vnet',
        position: { x: 18, y: 0.5, z: 1 },
        metadata: {},
      },
      {
        id: 'ext-browser',
        name: 'Client',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'browser',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...T6_EXT_CLIENT_POS },
        metadata: {},
      },
      {
        id: 'ext-internet',
        name: 'Internet',
        kind: 'resource',
        layer: 'resource',
        resourceType: 'internet',
        category: 'delivery',
        provider: 'azure',
        parentId: null,
        roles: ['external'],
        position: { ...T6_EXT_INTERNET_POS },
        metadata: {},
      },
    ],
    connections: [
      {
        id: 'conn-browser-internet',
        from: endpointId('ext-browser', 'output', 'http'),
        to: endpointId('ext-internet', 'input', 'http'),
        metadata: {},
      },
      // Internet → Gateway
      {
        id: 'conn-fs-inet-gw',
        from: endpointId('ext-internet', 'output', 'data'),
        to: endpointId('block-fs-gw', 'input', 'data'),
        metadata: {},
      },
      // Gateway → Compute (web frontend)
      {
        id: 'conn-fs-gw-web',
        from: endpointId('block-fs-gw', 'output', 'data'),
        to: endpointId('block-fs-web', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-fs-gw-apim',
        from: endpointId('block-fs-gw', 'output', 'data'),
        to: endpointId('block-fs-apim', 'input', 'data'),
        metadata: {},
      },
      {
        id: 'conn-fs-apim-api',
        from: endpointId('block-fs-apim', 'output', 'data'),
        to: endpointId('block-fs-api', 'input', 'data'),
        metadata: {},
      },
      // Compute → Storage
      {
        id: 'conn-fs-web-storage',
        from: endpointId('block-fs-web', 'output', 'data'),
        to: endpointId('block-fs-storage', 'input', 'data'),
        metadata: {},
      },
      // Function (API) → Database
      {
        id: 'conn-fs-api-db',
        from: endpointId('block-fs-api', 'output', 'data'),
        to: endpointId('block-fs-db', 'input', 'data'),
        metadata: {},
      },
      // Function (API) → Queue
      {
        id: 'conn-fs-api-queue',
        from: endpointId('block-fs-api', 'output', 'data'),
        to: endpointId('block-fs-queue', 'input', 'data'),
        metadata: {},
      },
      // Queue → Function (worker)
      {
        id: 'conn-fs-queue-worker',
        from: endpointId('block-fs-queue', 'output', 'data'),
        to: endpointId('block-fs-worker', 'input', 'data'),
        metadata: {},
      },
      // Event → Function (batch processor)
      {
        id: 'conn-fs-event-batch',
        from: endpointId('block-fs-event', 'output', 'data'),
        to: endpointId('block-fs-batch', 'input', 'data'),
        metadata: {},
      },
      // Timer → Function (batch processor)
      {
        id: 'conn-fs-timer-batch',
        from: endpointId('block-fs-timer', 'output', 'data'),
        to: endpointId('block-fs-batch', 'input', 'data'),
        metadata: {},
      },
      // Function (worker) → Storage
      {
        id: 'conn-fs-worker-storage',
        from: endpointId('block-fs-worker', 'output', 'data'),
        to: endpointId('block-fs-storage', 'input', 'data'),
        metadata: {},
      },
    ],
    externalActors: [
      { id: 'ext-browser', name: 'Client', type: 'browser', position: { ...T6_EXT_CLIENT_POS } },
      {
        id: 'ext-internet',
        name: 'Internet',
        type: 'internet',
        position: { ...T6_EXT_INTERNET_POS },
      },
    ],
  },
};

/**
 * Initialize all built-in templates.
 * Call this once at app startup.
 */
export function registerBuiltinTemplates(): void {
  registerTemplate(threeTierTemplate);
  registerTemplate(simpleComputeTemplate);
  registerTemplate(dataStorageTemplate);
  registerTemplate(serverlessHttpApiTemplate);
  registerTemplate(eventDrivenPipelineTemplate);
  registerTemplate(fullStackServerlessTemplate);
}
