import type { ArchitectureSnapshot, Scenario } from '../../../shared/types/learning';
import {
  type ContainerCapableResourceType,
  type ContainerLayer,
  endpointId,
} from '@cloudblocks/schema';
import { registerScenario } from './registry';

const CONTAINER_RESOURCE_TYPE: Record<ContainerLayer, ContainerCapableResourceType> = {
  global: 'virtual_network',
  edge: 'virtual_network',
  region: 'virtual_network',
  zone: 'virtual_network',
  subnet: 'subnet',
};

const threeTierInitialArchitecture: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointNetworkOnly: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointWithBlocks: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-gateway',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      subtype: 'application-gateway',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet1',
      position: { x: -1.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-compute',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      subtype: 'vm',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet1',
      position: { x: 1.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-database',
      name: 'Azure Database for PostgreSQL',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'azure-postgresql',
      category: 'data',
      subtype: 'azure-postgresql',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet2',
      position: { x: 0, y: 0.5, z: 0 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const threeTierScenario: Scenario = {
  id: 'scenario-three-tier',
  name: 'Build a Three-Tier Web Application',
  description:
    'Learn cloud architecture fundamentals by building a classic three-tier web application with gateway, compute, database, and storage.',
  difficulty: 'beginner',
  category: 'web-application',
  tags: ['three-tier', 'beginner', 'gateway', 'compute', 'database'],
  estimatedMinutes: 10,
  initialArchitecture: threeTierInitialArchitecture,
  steps: [
    {
      id: 'step-three-tier-create-network',
      order: 1,
      title: 'Create the Network',
      instruction: 'Create a Network container as the foundation for your cloud architecture.',
      hints: [
        'A Network container represents a Virtual Network (VNet) - the isolated network boundary for your cloud resources.',
        'Click the Network container button in the Command Card to add one to the canvas.',
      ],
      validationRules: [{ type: 'container-exists', containerLayer: 'region' }],
    },
    {
      id: 'step-three-tier-add-subnets',
      order: 2,
      title: 'Add Subnets',
      instruction: 'Add two Subnets inside your Network.',
      hints: [
        'Subnets divide your network into segments with separate IP ranges.',
        'In Azure, access control is managed by NSG and route tables, not by subnet type.',
        'Add two subnets from the Command Card.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
      checkpoint: threeTierCheckpointNetworkOnly,
    },
    {
      id: 'step-three-tier-place-resources',
      order: 3,
      title: 'Place Your Resources',
      instruction:
        'Place an Azure Application Gateway, an Azure Virtual Machine, and an Azure Database for PostgreSQL on your subnets.',
      hints: [
        'Gateways are the entry point for internet traffic.',
        'Databases should be isolated from direct internet exposure using NSG rules.',
        'Compute nodes can be on any subnet.',
      ],
      validationRules: [
        {
          type: 'block-exists',
          category: 'delivery',
          onContainerLayer: 'subnet',
        },
        { type: 'block-exists', category: 'compute' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
      checkpoint: threeTierCheckpointWithSubnets,
    },
    {
      id: 'step-three-tier-connect-flow',
      order: 4,
      title: 'Connect the Data Flow',
      instruction:
        'Connect Internet -> Azure Application Gateway -> Azure Virtual Machine -> Azure Database for PostgreSQL to establish the request flow.',
      hints: [
        'Use Connect mode to draw connections between resources.',
        'The data flow represents request direction: Internet -> Gateway -> Compute -> Database.',
        'Click the source block first, then click the target block to create a connection.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: threeTierCheckpointWithBlocks,
    },
    {
      id: 'step-three-tier-validate',
      order: 5,
      title: 'Validate Your Architecture',
      instruction: 'Ensure your architecture passes all validation rules.',
      hints: [
        'Open the Validation panel to see any errors.',
        'All blocks must be on valid plates, and all connections must follow the allowed flow rules.',
      ],
      validationRules: [{ type: 'architecture-valid' }],
    },
  ],
};

const serverlessApiInitialArchitecture: ArchitectureSnapshot = {
  name: 'Serverless API Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnsls-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const serverlessApiCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Serverless API Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnsls-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnsls-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnsls-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnsls-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnsls-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const serverlessApiScenario: Scenario = {
  id: 'scenario-serverless-api',
  name: 'Serverless HTTP API',
  description:
    'Build a serverless API architecture using functions, gateway, and managed data services.',
  difficulty: 'intermediate',
  category: 'serverless',
  tags: ['serverless', 'function', 'api', 'intermediate'],
  estimatedMinutes: 8,
  initialArchitecture: serverlessApiInitialArchitecture,
  steps: [
    {
      id: 'step-serverless-api-network-zones',
      order: 1,
      title: 'Set Up Network Zones',
      instruction: 'Add two Subnets — one for the gateway and one for data services.',
      hints: [
        'Even in serverless architectures, you need network boundaries.',
        'Use separate subnets to segment gateway traffic from data services.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
    },
    {
      id: 'step-serverless-api-deploy-components',
      order: 2,
      title: 'Deploy Serverless Components',
      instruction:
        'Place an Azure API Management block on a subnet, an Azure Functions block on the network container, and an Azure Cosmos DB block on a subnet.',
      hints: [
        'Functions are serverless compute - they run on the Network container, not a specific subnet.',
        'API Management is the public API front door - it receives HTTP requests and forwards them to your Function.',
        'Cosmos DB stores API data as a managed NoSQL service. Place it on a subnet.',
      ],
      validationRules: [
        {
          type: 'block-exists',
          category: 'delivery',
          onContainerLayer: 'subnet',
        },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'region' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
      checkpoint: serverlessApiCheckpointWithSubnets,
    },
    {
      id: 'step-serverless-api-wire-flow',
      order: 3,
      title: 'Wire the API Flow',
      instruction:
        'Connect Internet -> Azure API Management -> Azure Functions -> Azure Cosmos DB.',
      hints: [
        'The serverless flow: HTTP request hits API Management, triggers a Function, which queries Cosmos DB.',
        'Functions can connect to databases, storage, and queues.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
    },
    {
      id: 'step-serverless-api-validate',
      order: 4,
      title: 'Validate',
      instruction: 'Check that your serverless architecture is valid.',
      hints: [
        'Make sure all placements and connections follow the rules.',
        'Use the Validation panel to quickly identify any remaining placement or flow errors.',
      ],
      validationRules: [{ type: 'architecture-valid' }],
    },
  ],
};

const eventPipelineInitialArchitecture: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineCheckpointAfterStep2: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnevt-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      subtype: 'event-grid',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3, y: 0.5, z: -2.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      subtype: 'service-bus',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3, y: 0.5, z: 1.5 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineCheckpointWithAllBlocks: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnevt-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      subtype: 'event-grid',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3.5, y: 0.5, z: -2.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      subtype: 'service-bus',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3.5, y: 0.5, z: 1.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-fn-event',
      name: 'Azure Functions',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      subtype: 'functions',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 0, y: 0.5, z: -1.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-fn-batch',
      name: 'Azure Functions (Batch)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      subtype: 'functions',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 0, y: 0.5, z: 2 },
      metadata: {},
    },
    {
      id: 'block-scnevt-timer',
      name: 'Azure Functions Timer Trigger',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'timer-trigger',
      category: 'messaging',
      subtype: 'timer-trigger',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3.5, y: 0.5, z: -0.2 },
      metadata: {},
    },
    {
      id: 'block-scnevt-storage',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      subtype: 'blob-storage',
      provider: 'azure',
      parentId: 'container-scnevt-subnet',
      position: { x: 0, y: 0.5, z: 0 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineScenario: Scenario = {
  id: 'scenario-event-pipeline',
  name: 'Event-Driven Data Pipeline',
  description:
    'Design an event-driven data processing pipeline using events, queues, functions, and storage.',
  difficulty: 'advanced',
  category: 'data-pipeline',
  tags: ['event-driven', 'pipeline', 'queue', 'advanced'],
  estimatedMinutes: 12,
  initialArchitecture: eventPipelineInitialArchitecture,
  steps: [
    {
      id: 'step-event-pipeline-add-sources',
      order: 1,
      title: 'Add Event Sources',
      instruction: 'Place an Azure Event Grid and an Azure Service Bus on the Region container.',
      hints: [
        'Events and Queues are serverless resources that live on the Region container.',
        'Events trigger functions when something happens. Queues buffer messages for processing.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
      ],
    },
    {
      id: 'step-event-pipeline-add-functions',
      order: 2,
      title: 'Add Processing Functions',
      instruction:
        'Place two Azure Functions blocks on the Region container - one for event processing and one for batch processing.',
      hints: [
        'You need at least two functions: one triggered by events and one for batch processing.',
        'Functions run on the Region container, not in subnets.',
      ],
      validationRules: [{ type: 'min-block-count', category: 'compute', count: 2 }],
      checkpoint: eventPipelineCheckpointAfterStep2,
    },
    {
      id: 'step-event-pipeline-add-timer-storage',
      order: 3,
      title: 'Add a Timer Trigger and Blob Storage',
      instruction:
        'Place an Azure Functions Timer Trigger on the Region container and an Azure Blob Storage block on a Subnet.',
      hints: [
        'A Timer Trigger fires on a schedule (CRON) to drive periodic batch processing.',
        'Blob Storage stores the pipeline output. In real deployments, use Private Endpoints or firewall rules for network-level isolation.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
    },
    {
      id: 'step-event-pipeline-connect',
      order: 4,
      title: 'Connect the Pipeline',
      instruction:
        'Wire: Azure Event Grid -> Azure Functions, Azure Service Bus -> Azure Functions, Azure Functions Timer Trigger -> Azure Functions (Batch), and Azure Functions -> Azure Blob Storage.',
      hints: [
        'Events and Queues trigger Functions for processing.',
        'Functions process data and write results to Storage.',
        'Each trigger type connects to its designated processing function.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: eventPipelineCheckpointWithAllBlocks,
    },
    {
      id: 'step-event-pipeline-final-validate',
      order: 5,
      title: 'Final Validation',
      instruction: 'Validate your event-driven pipeline architecture.',
      hints: [
        'All serverless blocks must be on the Region container.',
        'Ensure at least 2 functions are present for the dual-processing pattern.',
      ],
      validationRules: [
        { type: 'architecture-valid' },
        { type: 'min-block-count', category: 'compute', count: 2 },
        { type: 'min-container-count', containerLayer: 'region', count: 1 },
      ],
    },
  ],
};

const simpleComputeInitialArchitecture: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const simpleComputeCheckpointNetworkOnly: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scncomp-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const simpleComputeCheckpointWithSubnet: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scncomp-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scncomp-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scncomp-vnet',
      position: { x: 0, y: 0.3, z: 0 },
      frame: { width: 6, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const simpleComputeCheckpointWithBlocks: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scncomp-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scncomp-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scncomp-vnet',
      position: { x: 0, y: 0.3, z: 0 },
      frame: { width: 6, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scncomp-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scncomp-subnet1',
      position: { x: -1.5, y: 0.5, z: -2 },
      metadata: {},
    },
    {
      id: 'block-scncomp-app',
      name: 'Azure App Service',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'app-service',
      category: 'compute',
      provider: 'azure',
      subtype: 'app-service',
      parentId: 'container-scncomp-subnet1',
      position: { x: 1.5, y: 0.5, z: 1 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const simpleComputeScenario: Scenario = {
  id: 'scenario-simple-compute',
  name: 'Simple Compute Setup',
  description:
    'Build a minimal web architecture with one network, one subnet, a gateway, and an app service.',
  difficulty: 'beginner',
  category: 'web-application',
  tags: ['simple', 'compute', 'app-service', 'beginner'],
  estimatedMinutes: 6,
  initialArchitecture: simpleComputeInitialArchitecture,
  steps: [
    {
      id: 'step-simple-compute-create-network',
      order: 1,
      title: 'Create the Network',
      instruction: 'Create a VNet container as the foundation for your compute setup.',
      hints: [
        'A VNet defines the network boundary for your resources.',
        'Use the Network container button in the Command Card.',
      ],
      validationRules: [{ type: 'container-exists', containerLayer: 'region' }],
    },
    {
      id: 'step-simple-compute-add-subnet',
      order: 2,
      title: 'Add a Subnet',
      instruction: 'Add one subnet inside your VNet.',
      hints: [
        'Subnets segment your VNet into smaller network zones.',
        'Add a single subnet from the Command Card.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 1 }],
      checkpoint: simpleComputeCheckpointNetworkOnly,
    },
    {
      id: 'step-simple-compute-place-tier',
      order: 3,
      title: 'Place Gateway and Compute',
      instruction: 'Place an Application Gateway and an App Service on the subnet.',
      hints: [
        'The Gateway receives inbound traffic from the internet.',
        'The App Service runs your web application.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'delivery', onContainerLayer: 'subnet' },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'subnet' },
      ],
      checkpoint: simpleComputeCheckpointWithSubnet,
    },
    {
      id: 'step-simple-compute-connect-flow',
      order: 4,
      title: 'Connect the Traffic Flow',
      instruction: 'Connect Internet -> Application Gateway -> App Service.',
      hints: [
        'Use Connect mode and click source first, then target.',
        'The expected request path is Internet -> Gateway -> App Service.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
      ],
      checkpoint: simpleComputeCheckpointWithBlocks,
    },
  ],
};

const dataStorageInitialArchitecture: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const dataStorageCheckpointNetworkOnly: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-app',
      name: 'App Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-data',
      name: 'Data Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageCheckpointAppTier: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-app',
      name: 'App Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-data',
      name: 'Data Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scndata-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scndata-subnet-app',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scndata-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scndata-subnet-app',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageCheckpointFull: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-app',
      name: 'App Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-data',
      name: 'Data Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scndata-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scndata-subnet-app',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scndata-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scndata-subnet-app',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scndata-db',
      name: 'Azure SQL Database',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'sql-database',
      category: 'data',
      provider: 'azure',
      subtype: 'sql-database',
      parentId: 'container-scndata-subnet-data',
      position: { x: 1.8, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scndata-blob',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      provider: 'azure',
      subtype: 'blob-storage',
      parentId: 'container-scndata-subnet-data',
      position: { x: 4.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageScenario: Scenario = {
  id: 'scenario-data-storage',
  name: 'Data Storage Backend',
  description:
    'Design an application and data-tier architecture with isolated subnets and managed storage services.',
  difficulty: 'intermediate',
  category: 'data-pipeline',
  tags: ['data', 'storage', 'database', 'isolation', 'intermediate'],
  estimatedMinutes: 10,
  initialArchitecture: dataStorageInitialArchitecture,
  steps: [
    {
      id: 'step-data-storage-create-network',
      order: 1,
      title: 'Create the Network',
      instruction: 'Create a VNet container for the backend architecture.',
      hints: [
        'Start with one VNet as your network boundary.',
        'You can place subnets and resources after the VNet is created.',
      ],
      validationRules: [{ type: 'container-exists', containerLayer: 'region' }],
    },
    {
      id: 'step-data-storage-add-subnets',
      order: 2,
      title: 'Add Application and Data Subnets',
      instruction: 'Add two subnets: one for application resources and one for data services.',
      hints: [
        'Separate app and data tiers to improve network isolation.',
        'Create exactly two subnets inside the VNet.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
      checkpoint: dataStorageCheckpointNetworkOnly,
    },
    {
      id: 'step-data-storage-deploy-app-tier',
      order: 3,
      title: 'Deploy the Application Tier',
      instruction: 'Place an Application Gateway and a VM on the first subnet.',
      hints: [
        'The gateway receives external traffic before forwarding to compute.',
        'Keep both app-tier resources on the same subnet for this scenario.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'delivery', onContainerLayer: 'subnet' },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'subnet' },
      ],
      checkpoint: dataStorageCheckpointWithSubnets,
    },
    {
      id: 'step-data-storage-add-data-services',
      order: 4,
      title: 'Add Data Services',
      instruction: 'Place a SQL Database and Blob Storage on the second subnet.',
      hints: [
        'Keep data resources in the dedicated data subnet.',
        'You need at least two data blocks for this step.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'data', onContainerLayer: 'subnet' },
        { type: 'min-block-count', category: 'data', count: 2 },
      ],
      checkpoint: dataStorageCheckpointAppTier,
    },
    {
      id: 'step-data-storage-wire-flow',
      order: 5,
      title: 'Wire the Data Flow',
      instruction:
        'Connect Internet -> Application Gateway -> VM -> SQL Database, and VM -> Blob Storage.',
      hints: [
        'Create the external ingress path first: Internet -> Gateway -> VM.',
        'Then connect the VM to both data services.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: dataStorageCheckpointFull,
    },
  ],
};

const fullStackInitialArchitecture: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const fullStackCheckpointFoundation: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnfs-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const fullStackCheckpointWebData: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnfs-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scnfs-subnet1',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scnfs-subnet1',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scnfs-db',
      name: 'Azure Database for PostgreSQL',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'sql-database',
      category: 'data',
      provider: 'azure',
      subtype: 'sql-database',
      parentId: 'container-scnfs-subnet2',
      position: { x: 1.8, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-storage',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      provider: 'azure',
      subtype: 'blob-storage',
      parentId: 'container-scnfs-subnet2',
      position: { x: 4.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
  ],
  connections: [
    {
      id: 'conn-scnfs-internet-gw',
      from: endpointId('ext-internet', 'output', 'data'),
      to: endpointId('block-scnfs-gw', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-gw-vm',
      from: endpointId('block-scnfs-gw', 'output', 'data'),
      to: endpointId('block-scnfs-vm', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-db',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-db', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-storage',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-storage', 'input', 'data'),
      metadata: {},
    },
  ],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const fullStackCheckpointWithServerless: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnfs-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scnfs-subnet1',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scnfs-subnet1',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scnfs-db',
      name: 'Azure Database for PostgreSQL',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'sql-database',
      category: 'data',
      provider: 'azure',
      subtype: 'sql-database',
      parentId: 'container-scnfs-subnet2',
      position: { x: 1.8, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-storage',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      provider: 'azure',
      subtype: 'blob-storage',
      parentId: 'container-scnfs-subnet2',
      position: { x: 4.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scnfs-api',
      name: 'Azure Functions',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      provider: 'azure',
      subtype: 'functions',
      parentId: 'container-scnfs-vnet',
      position: { x: -4, y: 0.5, z: 3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-worker',
      name: 'Azure Functions (Worker)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      provider: 'azure',
      subtype: 'functions',
      parentId: 'container-scnfs-vnet',
      position: { x: 0, y: 0.5, z: 3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-batch',
      name: 'Azure Functions (Batch)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      provider: 'azure',
      subtype: 'functions',
      parentId: 'container-scnfs-vnet',
      position: { x: 4, y: 0.5, z: 3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      provider: 'azure',
      subtype: 'service-bus',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.5, z: -3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      provider: 'azure',
      subtype: 'event-grid',
      parentId: 'container-scnfs-vnet',
      position: { x: 0, y: 0.5, z: -3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-timer',
      name: 'Azure Event Grid (Timer)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'operations',
      provider: 'azure',
      subtype: 'event-grid',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.5, z: -3 },
      metadata: {},
    },
  ],
  connections: [
    {
      id: 'conn-scnfs-internet-gw',
      from: endpointId('ext-internet', 'output', 'data'),
      to: endpointId('block-scnfs-gw', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-gw-vm',
      from: endpointId('block-scnfs-gw', 'output', 'data'),
      to: endpointId('block-scnfs-vm', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-db',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-db', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-storage',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-storage', 'input', 'data'),
      metadata: {},
    },
  ],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const fullStackScenario: Scenario = {
  id: 'scenario-full-stack',
  name: 'Full-Stack Web App with Event Processing',
  description:
    'Build a full-stack architecture with web, data, and serverless event processing layers.',
  difficulty: 'advanced',
  category: 'serverless',
  tags: ['full-stack', 'serverless', 'event-driven', 'advanced'],
  estimatedMinutes: 15,
  initialArchitecture: fullStackInitialArchitecture,
  steps: [
    {
      id: 'step-full-stack-foundation',
      order: 1,
      title: 'Build the Network Foundation',
      instruction: 'Create one VNet and two subnets for web and data tiers.',
      hints: [
        'You need a VNet first, then two subnets under it.',
        'Subnet 1 is for web tier resources, Subnet 2 is for data services.',
      ],
      validationRules: [
        { type: 'container-exists', containerLayer: 'region' },
        { type: 'min-container-count', containerLayer: 'subnet', count: 2 },
      ],
    },
    {
      id: 'step-full-stack-web-tier',
      order: 2,
      title: 'Deploy the Web Tier',
      instruction:
        'Place an Application Gateway and a VM on Subnet 1, then connect Internet -> Gateway -> VM.',
      hints: [
        'Both gateway and VM should be placed on a subnet.',
        'Complete ingress routing before adding data or serverless components.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'delivery', onContainerLayer: 'subnet' },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'subnet' },
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
      ],
      checkpoint: fullStackCheckpointFoundation,
    },
    {
      id: 'step-full-stack-data-services',
      order: 3,
      title: 'Add Data Services',
      instruction:
        'Place PostgreSQL and Blob Storage on Subnet 2, then connect VM -> Database and VM -> Storage.',
      hints: [
        'Data services should be isolated on the data subnet.',
        'At least one compute-to-data connection is required for validation.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'data', onContainerLayer: 'subnet' },
        { type: 'min-block-count', category: 'data', count: 2 },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: fullStackCheckpointWebData,
    },
    {
      id: 'step-full-stack-serverless-layer',
      order: 4,
      title: 'Build the Serverless Layer',
      instruction:
        'Place 3 Functions, Service Bus, Event Grid, and a Timer Trigger on the VNet. Connect Queue -> Worker Function, Event -> Batch Function, and Timer -> Batch Function.',
      hints: [
        'Serverless resources in this scenario are placed on the VNet container.',
        'Use messaging-to-compute connections for queue and event triggers.',
      ],
      validationRules: [
        { type: 'min-block-count', category: 'compute', count: 4 },
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
      ],
      checkpoint: fullStackCheckpointWithServerless,
    },
    {
      id: 'step-full-stack-final-validation',
      order: 5,
      title: 'Final Validation',
      instruction: 'Validate the complete architecture.',
      hints: [
        'Check placement and connection rules in the Validation panel.',
        'Ensure all required layers and compute components are present.',
      ],
      validationRules: [
        { type: 'architecture-valid' },
        { type: 'min-block-count', category: 'compute', count: 4 },
        { type: 'min-container-count', containerLayer: 'subnet', count: 2 },
      ],
    },
  ],
};

export function registerBuiltinScenarios(): void {
  registerScenario(threeTierScenario);
  registerScenario(serverlessApiScenario);
  registerScenario(eventPipelineScenario);
  registerScenario(simpleComputeScenario);
  registerScenario(dataStorageScenario);
  registerScenario(fullStackScenario);
}
