import type { ArchitectureSnapshot, Scenario } from '../../../shared/types/learning';
import type { ContainerCapableResourceType, ContainerLayer } from '@cloudblocks/schema';
import { registerScenario } from './registry';

const CONTAINER_RESOURCE_TYPE: Record<ContainerLayer, ContainerCapableResourceType> = {
  global: 'virtual_network',
  edge: 'virtual_network',
  region: 'virtual_network',
  zone: 'virtual_network',
  subnet: 'subnet',
};

const threeTierInitialArchitecture: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointNetworkOnly: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointWithBlocks: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-gateway',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      subtype: 'application-gateway',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet1',
      position: { x: -1.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-compute',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      subtype: 'vm',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet1',
      position: { x: 1.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-database',
      name: 'Azure Database for PostgreSQL',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'azure-postgresql',
      category: 'data',
      subtype: 'azure-postgresql',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet2',
      position: { x: 0, y: 0.5, z: 0 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -9, y: 0, z: -8 } },
  ],
};

const threeTierScenario: Scenario = {
  id: 'scenario-three-tier',
  name: 'Build a Three-Tier Web Application',
  description:
    'Learn cloud architecture fundamentals by building a classic three-tier web application with gateway, compute, database, and storage.',
  difficulty: 'beginner',
  category: 'web-application',
  tags: ['three-tier', 'beginner', 'gateway', 'compute', 'database'],
  estimatedMinutes: 10,
  initialArchitecture: threeTierInitialArchitecture,
  steps: [
    {
      id: 'step-three-tier-create-network',
      order: 1,
      title: 'Create the Network',
      instruction: 'Create a Network container as the foundation for your cloud architecture.',
      hints: [
        'A Network container represents a Virtual Network (VNet) - the isolated network boundary for your cloud resources.',
        'Click the Network container button in the Command Card to add one to the canvas.',
      ],
      validationRules: [{ type: 'container-exists', containerLayer: 'region' }],
    },
    {
      id: 'step-three-tier-add-subnets',
      order: 2,
      title: 'Add Subnets',
      instruction: 'Add two Subnets inside your Network.',
      hints: [
        'Subnets divide your network into segments with separate IP ranges.',
        'In Azure, access control is managed by NSG and route tables, not by subnet type.',
        'Add two subnets from the Command Card.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
      checkpoint: threeTierCheckpointNetworkOnly,
    },
    {
      id: 'step-three-tier-place-resources',
      order: 3,
      title: 'Place Your Resources',
      instruction:
        'Place an Azure Application Gateway, an Azure Virtual Machine, and an Azure Database for PostgreSQL on your subnets.',
      hints: [
        'Gateways are the entry point for internet traffic.',
        'Databases should be isolated from direct internet exposure using NSG rules.',
        'Compute nodes can be on any subnet.',
      ],
      validationRules: [
        {
          type: 'block-exists',
          category: 'delivery',
          onContainerLayer: 'subnet',
        },
        { type: 'block-exists', category: 'compute' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
      checkpoint: threeTierCheckpointWithSubnets,
    },
    {
      id: 'step-three-tier-connect-flow',
      order: 4,
      title: 'Connect the Data Flow',
      instruction:
        'Connect Internet -> Azure Application Gateway -> Azure Virtual Machine -> Azure Database for PostgreSQL to establish the request flow.',
      hints: [
        'Use Connect mode to draw connections between resources.',
        'The data flow represents request direction: Internet -> Gateway -> Compute -> Database.',
        'Click the source block first, then click the target block to create a connection.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: threeTierCheckpointWithBlocks,
    },
    {
      id: 'step-three-tier-validate',
      order: 5,
      title: 'Validate Your Architecture',
      instruction: 'Ensure your architecture passes all validation rules.',
      hints: [
        'Open the Validation panel to see any errors.',
        'All blocks must be on valid plates, and all connections must follow the allowed flow rules.',
      ],
      validationRules: [{ type: 'architecture-valid' }],
    },
  ],
};

const serverlessApiInitialArchitecture: ArchitectureSnapshot = {
  name: 'Serverless API Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnsls-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -9, y: 0, z: -8 } },
  ],
};

const serverlessApiCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Serverless API Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnsls-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnsls-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnsls-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnsls-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnsls-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -9, y: 0, z: -8 } },
  ],
};

const serverlessApiScenario: Scenario = {
  id: 'scenario-serverless-api',
  name: 'Serverless HTTP API',
  description:
    'Build a serverless API architecture using functions, gateway, and managed data services.',
  difficulty: 'intermediate',
  category: 'serverless',
  tags: ['serverless', 'function', 'api', 'intermediate'],
  estimatedMinutes: 8,
  initialArchitecture: serverlessApiInitialArchitecture,
  steps: [
    {
      id: 'step-serverless-api-network-zones',
      order: 1,
      title: 'Set Up Network Zones',
      instruction: 'Add two Subnets — one for the gateway and one for data services.',
      hints: [
        'Even in serverless architectures, you need network boundaries.',
        'Use separate subnets to segment gateway traffic from data services.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
    },
    {
      id: 'step-serverless-api-deploy-components',
      order: 2,
      title: 'Deploy Serverless Components',
      instruction:
        'Place an Azure API Management block on a subnet, an Azure Functions block on the network container, and an Azure Cosmos DB block on a subnet.',
      hints: [
        'Functions are serverless compute - they run on the Network container, not a specific subnet.',
        'API Management is the public API front door - it receives HTTP requests and forwards them to your Function.',
        'Cosmos DB stores API data as a managed NoSQL service. Place it on a subnet.',
      ],
      validationRules: [
        {
          type: 'block-exists',
          category: 'delivery',
          onContainerLayer: 'subnet',
        },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'region' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
      checkpoint: serverlessApiCheckpointWithSubnets,
    },
    {
      id: 'step-serverless-api-wire-flow',
      order: 3,
      title: 'Wire the API Flow',
      instruction:
        'Connect Internet -> Azure API Management -> Azure Functions -> Azure Cosmos DB.',
      hints: [
        'The serverless flow: HTTP request hits API Management, triggers a Function, which queries Cosmos DB.',
        'Functions can connect to databases, storage, and queues.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
    },
    {
      id: 'step-serverless-api-validate',
      order: 4,
      title: 'Validate',
      instruction: 'Check that your serverless architecture is valid.',
      hints: [
        'Make sure all placements and connections follow the rules.',
        'Use the Validation panel to quickly identify any remaining placement or flow errors.',
      ],
      validationRules: [{ type: 'architecture-valid' }],
    },
  ],
};

const eventPipelineInitialArchitecture: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineCheckpointAfterStep2: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnevt-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      subtype: 'event-grid',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3, y: 0.5, z: -2.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      subtype: 'service-bus',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3, y: 0.5, z: 1.5 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineCheckpointWithAllBlocks: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnevt-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      subtype: 'event-grid',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3.5, y: 0.5, z: -2.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      subtype: 'service-bus',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3.5, y: 0.5, z: 1.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-fn-event',
      name: 'Azure Functions',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      subtype: 'functions',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 0, y: 0.5, z: -1.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-fn-batch',
      name: 'Azure Functions (Batch)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      subtype: 'functions',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 0, y: 0.5, z: 2 },
      metadata: {},
    },
    {
      id: 'block-scnevt-timer',
      name: 'Azure Functions Timer Trigger',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'timer-trigger',
      category: 'messaging',
      subtype: 'timer-trigger',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3.5, y: 0.5, z: -0.2 },
      metadata: {},
    },
    {
      id: 'block-scnevt-storage',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      subtype: 'blob-storage',
      provider: 'azure',
      parentId: 'container-scnevt-subnet',
      position: { x: 0, y: 0.5, z: 0 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineScenario: Scenario = {
  id: 'scenario-event-pipeline',
  name: 'Event-Driven Data Pipeline',
  description:
    'Design an event-driven data processing pipeline using events, queues, functions, and storage.',
  difficulty: 'advanced',
  category: 'data-pipeline',
  tags: ['event-driven', 'pipeline', 'queue', 'advanced'],
  estimatedMinutes: 12,
  initialArchitecture: eventPipelineInitialArchitecture,
  steps: [
    {
      id: 'step-event-pipeline-add-sources',
      order: 1,
      title: 'Add Event Sources',
      instruction: 'Place an Azure Event Grid and an Azure Service Bus on the Region container.',
      hints: [
        'Events and Queues are serverless resources that live on the Region container.',
        'Events trigger functions when something happens. Queues buffer messages for processing.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
      ],
    },
    {
      id: 'step-event-pipeline-add-functions',
      order: 2,
      title: 'Add Processing Functions',
      instruction:
        'Place two Azure Functions blocks on the Region container - one for event processing and one for batch processing.',
      hints: [
        'You need at least two functions: one triggered by events and one for batch processing.',
        'Functions run on the Region container, not in subnets.',
      ],
      validationRules: [{ type: 'min-block-count', category: 'compute', count: 2 }],
      checkpoint: eventPipelineCheckpointAfterStep2,
    },
    {
      id: 'step-event-pipeline-add-timer-storage',
      order: 3,
      title: 'Add a Timer Trigger and Blob Storage',
      instruction:
        'Place an Azure Functions Timer Trigger on the Region container and an Azure Blob Storage block on a Subnet.',
      hints: [
        'A Timer Trigger fires on a schedule (CRON) to drive periodic batch processing.',
        'Blob Storage stores the pipeline output. In real deployments, use Private Endpoints or firewall rules for network-level isolation.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
    },
    {
      id: 'step-event-pipeline-connect',
      order: 4,
      title: 'Connect the Pipeline',
      instruction:
        'Wire: Azure Event Grid -> Azure Functions, Azure Service Bus -> Azure Functions, Azure Functions Timer Trigger -> Azure Functions (Batch), and Azure Functions -> Azure Blob Storage.',
      hints: [
        'Events and Queues trigger Functions for processing.',
        'Functions process data and write results to Storage.',
        'Each trigger type connects to its designated processing function.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: eventPipelineCheckpointWithAllBlocks,
    },
    {
      id: 'step-event-pipeline-final-validate',
      order: 5,
      title: 'Final Validation',
      instruction: 'Validate your event-driven pipeline architecture.',
      hints: [
        'All serverless blocks must be on the Region container.',
        'Ensure at least 2 functions are present for the dual-processing pattern.',
      ],
      validationRules: [
        { type: 'architecture-valid' },
        { type: 'min-block-count', category: 'compute', count: 2 },
        { type: 'min-container-count', containerLayer: 'region', count: 1 },
      ],
    },
  ],
};

export function registerBuiltinScenarios(): void {
  registerScenario(threeTierScenario);
  registerScenario(serverlessApiScenario);
  registerScenario(eventPipelineScenario);
}
