import type { ArchitectureSnapshot, Scenario } from '../../../shared/types/learning';
import {
  type ContainerCapableResourceType,
  type ContainerLayer,
  endpointId,
} from '@cloudblocks/schema';
import { registerScenario } from './registry';

const CONTAINER_RESOURCE_TYPE: Record<ContainerLayer, ContainerCapableResourceType> = {
  global: 'virtual_network',
  edge: 'virtual_network',
  region: 'virtual_network',
  zone: 'virtual_network',
  subnet: 'subnet',
};

const threeTierInitialArchitecture: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointNetworkOnly: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const threeTierCheckpointWithBlocks: ArchitectureSnapshot = {
  name: 'Three-Tier Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scn3tier-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scn3tier-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scn3tier-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-gateway',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      subtype: 'application-gateway',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet1',
      position: { x: -1.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-compute',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      subtype: 'vm',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet1',
      position: { x: 1.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scn3tier-database',
      name: 'Azure Database for PostgreSQL',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'azure-postgresql',
      category: 'data',
      subtype: 'azure-postgresql',
      provider: 'azure',
      parentId: 'container-scn3tier-subnet2',
      position: { x: 0, y: 0.5, z: 0 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const threeTierScenario: Scenario = {
  id: 'scenario-three-tier',
  name: 'Build a Three-Tier Web Application',
  description:
    'Learn cloud architecture basics by building a classic three-tier web application — a gateway that receives traffic, a server that runs your app, and a database that stores your data.',
  difficulty: 'beginner',
  category: 'web-application',
  tags: ['three-tier', 'beginner', 'gateway', 'compute', 'database'],
  estimatedMinutes: 10,
  initialArchitecture: threeTierInitialArchitecture,
  steps: [
    {
      id: 'step-three-tier-create-network',
      order: 1,
      title: 'Create Your Network',
      instruction:
        'Create a Network container — your private cloud network that keeps resources isolated and secure.',
      hints: [
        'A Network container represents a Virtual Network (VNet), the foundation of any cloud architecture. Think of it as a private, walled-off section of the cloud just for you.',
        'Click the Network container button in the Command Card to add one to the canvas.',
      ],
      validationRules: [{ type: 'container-exists', containerLayer: 'region' }],
    },
    {
      id: 'step-three-tier-add-subnets',
      order: 2,
      title: 'Add Subnets',
      instruction:
        'Add two Subnets inside your Network. Subnets are smaller sections within your network that group related resources together.',
      hints: [
        'Subnets help you organize resources — for example, one Subnet for your web server and another for your database.',
        'Placing resources on separate Subnets improves security by keeping them isolated from each other.',
        'Add two Subnets from the Command Card.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
      checkpoint: threeTierCheckpointNetworkOnly,
    },
    {
      id: 'step-three-tier-place-resources',
      order: 3,
      title: 'Place Your Resources',
      instruction:
        '1. Place an Application Gateway on a Subnet — the entry point that receives internet traffic and routes it to your app.\n2. Place a Virtual Machine on a Subnet — a cloud computer that runs your application code.\n3. Place a Database for PostgreSQL on the other Subnet — a managed database that stores your application data.',
      hints: [
        'The Application Gateway goes on one Subnet — it receives requests from the internet and forwards them to your app.',
        'Place the Database on a separate Subnet to keep it isolated from direct internet access.',
        'The Virtual Machine can go on either Subnet.',
      ],
      validationRules: [
        {
          type: 'block-exists',
          category: 'delivery',
          onContainerLayer: 'subnet',
        },
        { type: 'block-exists', category: 'compute' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
      checkpoint: threeTierCheckpointWithSubnets,
    },
    {
      id: 'step-three-tier-connect-flow',
      order: 4,
      title: 'Connect the Data Flow',
      instruction:
        '1. Draw a connection from Internet to Application Gateway.\n2. Draw a connection from Application Gateway to Virtual Machine.\n3. Draw a connection from Virtual Machine to Database for PostgreSQL.',
      hints: [
        'Switch to Connect mode by clicking the Connect button in the toolbar.',
        'Click the source block first, then click the target block to create a connection.',
        'The arrows show the direction data travels: users send requests to the Gateway, which forwards them to the Virtual Machine, which queries the Database.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: threeTierCheckpointWithBlocks,
    },
    {
      id: 'step-three-tier-validate',
      order: 5,
      title: 'Validate Your Architecture',
      instruction:
        'Check that your architecture passes all validation rules. Open the Validation panel to review any issues.',
      hints: [
        'The Validation panel shows errors if blocks are misplaced or connections are missing.',
        'All blocks must be placed inside the correct containers, and all connections must follow the allowed flow rules.',
        '🎉 Congratulations! You built a classic three-tier web architecture. Next, try the Serverless HTTP API scenario to learn a serverless pattern!',
      ],
      validationRules: [{ type: 'architecture-valid' }],
    },
  ],
};

const serverlessApiInitialArchitecture: ArchitectureSnapshot = {
  name: 'Serverless API Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnsls-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const serverlessApiCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Serverless API Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnsls-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnsls-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnsls-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnsls-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnsls-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const serverlessApiScenario: Scenario = {
  id: 'scenario-serverless-api',
  name: 'Serverless HTTP API',
  description:
    'Build a serverless API (Application Programming Interface) — an architecture where your code runs on-demand without managing servers. You will use functions, an API gateway, and a managed database.',
  difficulty: 'intermediate',
  category: 'serverless',
  tags: ['serverless', 'function', 'api', 'intermediate'],
  estimatedMinutes: 8,
  initialArchitecture: serverlessApiInitialArchitecture,
  steps: [
    {
      id: 'step-serverless-api-network-zones',
      order: 1,
      title: 'Set Up Network Zones',
      instruction:
        '1. Create a Network container \u2014 your private cloud network that keeps your resources isolated.\n2. Add two Subnets inside the Network \u2014 one for the API gateway and one for data services. Subnets group related resources together.',
      hints: [
        'Even in serverless architectures, you still need network boundaries to organize and secure your resources.',
        'Use separate Subnets to keep gateway traffic separate from data services.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
    },
    {
      id: 'step-serverless-api-deploy-components',
      order: 2,
      title: 'Deploy Serverless Components',
      instruction:
        '1. Place an Azure API Management block on a Subnet — this is the front door that receives web requests.\n2. Place an Azure Functions block on the Network container — this is the serverless code that processes requests.\n3. Place an Azure Cosmos DB block on a Subnet — this is the database that stores your API data.',
      hints: [
        'Azure Functions (serverless code that runs on-demand) belong on the Network container, not a specific Subnet.',
        'API Management acts as the public entry point — it receives web requests and routes them to your Function.',
        'Cosmos DB is a managed cloud database. Place it on a Subnet for network isolation.',
      ],
      validationRules: [
        {
          type: 'block-exists',
          category: 'delivery',
          onContainerLayer: 'subnet',
        },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'region' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
      checkpoint: serverlessApiCheckpointWithSubnets,
    },
    {
      id: 'step-serverless-api-wire-flow',
      order: 3,
      title: 'Wire the API Flow',
      instruction:
        '1. Draw a connection from Internet to API Management.\n2. Draw a connection from API Management to Azure Functions.\n3. Draw a connection from Azure Functions to Cosmos DB.',
      hints: [
        'The flow shows how a request travels: a user sends an HTTP (Hypertext Transfer Protocol) request, API Management receives it, triggers a Function, which reads or writes data in Cosmos DB.',
        'Switch to Connect mode, then click the source block followed by the target block.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
    },
    {
      id: 'step-serverless-api-validate',
      order: 4,
      title: 'Validate Your Architecture',
      instruction: 'Check that your serverless architecture passes all validation rules.',
      hints: [
        'Open the Validation panel to see if any placements or connections need fixing.',
        'All blocks must be inside the correct containers, and connections must follow allowed patterns.',
        '🎉 Congratulations! You built a serverless API. Next, try the Event-Driven Data Pipeline scenario to learn asynchronous event processing!',
      ],
      validationRules: [{ type: 'architecture-valid' }],
    },
  ],
};

const eventPipelineInitialArchitecture: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineCheckpointAfterStep2: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnevt-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      subtype: 'event-grid',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3, y: 0.5, z: -2.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      subtype: 'service-bus',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3, y: 0.5, z: 1.5 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineCheckpointWithAllBlocks: ArchitectureSnapshot = {
  name: 'Event Pipeline Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnevt-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnevt-subnet',
      name: 'Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnevt-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      subtype: 'event-grid',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3.5, y: 0.5, z: -2.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      subtype: 'service-bus',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: -3.5, y: 0.5, z: 1.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-fn-event',
      name: 'Azure Functions',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      subtype: 'functions',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 0, y: 0.5, z: -1.5 },
      metadata: {},
    },
    {
      id: 'block-scnevt-fn-batch',
      name: 'Azure Functions (Batch)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      subtype: 'functions',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 0, y: 0.5, z: 2 },
      metadata: {},
    },
    {
      id: 'block-scnevt-timer',
      name: 'Azure Functions Timer Trigger',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'timer-trigger',
      category: 'messaging',
      subtype: 'timer-trigger',
      provider: 'azure',
      parentId: 'container-scnevt-vnet',
      position: { x: 3.5, y: 0.5, z: -0.2 },
      metadata: {},
    },
    {
      id: 'block-scnevt-storage',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      subtype: 'blob-storage',
      provider: 'azure',
      parentId: 'container-scnevt-subnet',
      position: { x: 0, y: 0.5, z: 0 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const eventPipelineScenario: Scenario = {
  id: 'scenario-event-pipeline',
  name: 'Event-Driven Data Pipeline',
  description:
    'Design an event-driven pipeline — an architecture where events (like a file upload or a timer) automatically trigger processing functions that transform data and store results.',
  difficulty: 'advanced',
  category: 'data-pipeline',
  tags: ['event-driven', 'pipeline', 'queue', 'advanced'],
  estimatedMinutes: 12,
  initialArchitecture: eventPipelineInitialArchitecture,
  steps: [
    {
      id: 'step-event-pipeline-add-sources',
      order: 1,
      title: 'Add Event Sources',
      instruction:
        '1. Create a Network container \u2014 your private cloud network.\n2. Place an Event Grid on the Network container \u2014 it detects when something happens (like a file upload) and notifies other services.\n3. Place a Service Bus on the Network container \u2014 a message queue that buffers work items for processing.',
      hints: [
        'Event Grid detects when something happens (like a file upload) and notifies other services. Service Bus is a message queue that buffers work items for processing.',
        'Both are messaging resources and belong on the Network container, not inside a Subnet.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
      ],
    },
    {
      id: 'step-event-pipeline-add-functions',
      order: 2,
      title: 'Add Processing Functions',
      instruction:
        '1. Place an Azure Functions block on the Network container for real-time event processing.\n2. Place a second Azure Functions block on the Network container for batch processing (handling large volumes of data at once).',
      hints: [
        'Azure Functions are small pieces of code that run automatically when triggered, without managing servers.',
        'You need two functions: one handles incoming events and another processes batches of data. Both belong on the Network container.',
      ],
      validationRules: [{ type: 'min-block-count', category: 'compute', count: 2 }],
      checkpoint: eventPipelineCheckpointAfterStep2,
    },
    {
      id: 'step-event-pipeline-add-timer-storage',
      order: 3,
      title: 'Add a Timer and Storage',
      instruction:
        '1. Create a Subnet inside your Network \u2014 for storing pipeline output.\n2. Place a Timer Trigger on the Network container \u2014 a scheduled task that runs automatically at set intervals.\n3. Place a Blob Storage block on the Subnet \u2014 cloud file storage for your pipeline output.',
      hints: [
        'The Timer Trigger fires on a schedule (e.g., every hour) to kick off batch processing jobs.',
        'Blob Storage holds the final output of your pipeline. Place it on a Subnet for network isolation.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        {
          type: 'block-exists',
          category: 'data',
          onContainerLayer: 'subnet',
        },
      ],
    },
    {
      id: 'step-event-pipeline-connect',
      order: 4,
      title: 'Connect the Pipeline',
      instruction:
        '1. Draw a connection from Event Grid to the event handler Function.\n2. Draw a connection from Service Bus to the event handler Function.\n3. Draw a connection from Timer Trigger to the batch processor Function.\n4. Draw a connection from the batch processor Function to Blob Storage.',
      hints: [
        'Events and queues trigger Functions to start processing data.',
        'Functions process data and write results to Storage.',
        'Each source connects to its designated processing function — switch to Connect mode and click source then target.',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: eventPipelineCheckpointWithAllBlocks,
    },
    {
      id: 'step-event-pipeline-final-validate',
      order: 5,
      title: 'Validate Your Architecture',
      instruction:
        'Validate your event-driven pipeline architecture. Open the Validation panel to check for any issues.',
      hints: [
        'All messaging and compute blocks should be on the Network container.',
        'Ensure at least 2 Functions are present for the dual-processing pattern (event + batch).',
        '🎉 Congratulations! You built an event-driven data pipeline. Next, try the Full-Stack Web App with Event Processing scenario to learn a complete architecture!',
      ],
      validationRules: [
        { type: 'architecture-valid' },
        { type: 'min-block-count', category: 'compute', count: 2 },
        { type: 'min-container-count', containerLayer: 'region', count: 1 },
      ],
    },
  ],
};

const simpleComputeInitialArchitecture: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const simpleComputeCheckpointNetworkOnly: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scncomp-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const simpleComputeCheckpointWithSubnet: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scncomp-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scncomp-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scncomp-vnet',
      position: { x: 0, y: 0.3, z: 0 },
      frame: { width: 6, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [],
};

const simpleComputeCheckpointWithBlocks: ArchitectureSnapshot = {
  name: 'Simple Compute Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scncomp-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scncomp-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scncomp-vnet',
      position: { x: 0, y: 0.3, z: 0 },
      frame: { width: 6, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scncomp-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scncomp-subnet1',
      position: { x: -1.5, y: 0.5, z: -2 },
      metadata: {},
    },
    {
      id: 'block-scncomp-app',
      name: 'Azure App Service',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'app-service',
      category: 'compute',
      provider: 'azure',
      subtype: 'app-service',
      parentId: 'container-scncomp-subnet1',
      position: { x: 1.5, y: 0.5, z: 1 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const simpleComputeScenario: Scenario = {
  id: 'scenario-simple-compute',
  name: 'Simple Compute Setup',
  description:
    'Build the simplest cloud web setup — one network, one Subnet, a gateway to receive traffic, and a managed app service to run your website.',
  difficulty: 'beginner',
  category: 'web-application',
  tags: ['simple', 'compute', 'app-service', 'beginner'],
  estimatedMinutes: 6,
  initialArchitecture: simpleComputeInitialArchitecture,
  steps: [
    {
      id: 'step-simple-compute-create-network',
      order: 1,
      title: 'Create Your Network',
      instruction:
        'Create a Network container — your private cloud network that isolates your resources from the public internet.',
      hints: [
        'A Network container represents a Virtual Network (VNet). It is the first thing you create in any cloud architecture.',
        'Click the Network container button in the Command Card to add one to the canvas.',
      ],
      validationRules: [{ type: 'container-exists', containerLayer: 'region' }],
    },
    {
      id: 'step-simple-compute-add-subnet',
      order: 2,
      title: 'Add a Subnet',
      instruction:
        'Add one Subnet inside your Network. A Subnet is a smaller section that groups related resources together.',
      hints: [
        'Subnets help organize your network — in this simple setup, one Subnet is enough to hold all your resources.',
        'Add a Subnet from the Command Card.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 1 }],
      checkpoint: simpleComputeCheckpointNetworkOnly,
    },
    {
      id: 'step-simple-compute-place-tier',
      order: 3,
      title: 'Place Gateway and Compute',
      instruction:
        '1. Place an Application Gateway on the Subnet — the entry point that receives internet traffic.\n2. Place an App Service on the Subnet — a managed platform that runs your web app without requiring you to manage the underlying server.',
      hints: [
        'The Application Gateway receives incoming requests from the internet and forwards them to your app.',
        'The App Service runs your web application without requiring you to manage the underlying server.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'delivery', onContainerLayer: 'subnet' },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'subnet' },
      ],
      checkpoint: simpleComputeCheckpointWithSubnet,
    },
    {
      id: 'step-simple-compute-connect-flow',
      order: 4,
      title: 'Connect the Traffic Flow',
      instruction:
        '1. Draw a connection from Internet to Application Gateway.\n2. Draw a connection from Application Gateway to App Service.',
      hints: [
        'Switch to Connect mode, then click the source block followed by the target block.',
        'The arrows show how traffic flows: users reach the Gateway, which forwards requests to the App Service.',
        '🎉 Congratulations! You built the simplest cloud web setup. Next, try the Three-Tier Web Application scenario to learn how to add a database layer!',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
      ],
      checkpoint: simpleComputeCheckpointWithBlocks,
    },
  ],
};

const dataStorageInitialArchitecture: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const dataStorageCheckpointNetworkOnly: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageCheckpointWithSubnets: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-app',
      name: 'App Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-data',
      name: 'Data Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageCheckpointAppTier: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-app',
      name: 'App Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-data',
      name: 'Data Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scndata-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scndata-subnet-app',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scndata-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scndata-subnet-app',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageCheckpointFull: ArchitectureSnapshot = {
  name: 'Data Storage Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scndata-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-app',
      name: 'App Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scndata-subnet-data',
      name: 'Data Subnet',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scndata-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scndata-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scndata-subnet-app',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scndata-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scndata-subnet-app',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scndata-db',
      name: 'Azure SQL Database',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'sql-database',
      category: 'data',
      provider: 'azure',
      subtype: 'sql-database',
      parentId: 'container-scndata-subnet-data',
      position: { x: 1.8, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scndata-blob',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      provider: 'azure',
      subtype: 'blob-storage',
      parentId: 'container-scndata-subnet-data',
      position: { x: 4.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const dataStorageScenario: Scenario = {
  id: 'scenario-data-storage',
  name: 'Data Storage Backend',
  description:
    'Design a backend architecture with separate Subnets for your application and data services — learn how network isolation keeps databases secure.',
  difficulty: 'intermediate',
  category: 'data-pipeline',
  tags: ['data', 'storage', 'database', 'isolation', 'intermediate'],
  estimatedMinutes: 10,
  initialArchitecture: dataStorageInitialArchitecture,
  steps: [
    {
      id: 'step-data-storage-create-network',
      order: 1,
      title: 'Create the Network',
      instruction:
        'Create a Network container — the private cloud network where all your backend resources will live.',
      hints: [
        'The Network container (Virtual Network / VNet) is always the first step in any cloud architecture.',
        'Once the network is created, you can add Subnets and resources inside it.',
      ],
      validationRules: [{ type: 'container-exists', containerLayer: 'region' }],
    },
    {
      id: 'step-data-storage-add-subnets',
      order: 2,
      title: 'Add Application and Data Subnets',
      instruction:
        '1. Add a Subnet for your application resources (gateway + server).\n2. Add a second Subnet for data services (database + storage).',
      hints: [
        'Putting app and data resources on separate Subnets improves security — data services are isolated from direct external access.',
        'Create exactly two Subnets inside the Network container.',
      ],
      validationRules: [{ type: 'min-container-count', containerLayer: 'subnet', count: 2 }],
      checkpoint: dataStorageCheckpointNetworkOnly,
    },
    {
      id: 'step-data-storage-deploy-app-tier',
      order: 3,
      title: 'Deploy the Application Tier',
      instruction:
        '1. Place an Application Gateway on the first Subnet — the entry point that receives internet traffic.\n2. Place a Virtual Machine on the first Subnet — your cloud computer that runs the application.',
      hints: [
        'The Application Gateway receives external traffic and forwards it to your server.',
        'Keep both app-tier resources on the same Subnet for this scenario.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'delivery', onContainerLayer: 'subnet' },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'subnet' },
      ],
      checkpoint: dataStorageCheckpointWithSubnets,
    },
    {
      id: 'step-data-storage-add-data-services',
      order: 4,
      title: 'Add Data Services',
      instruction:
        '1. Place a SQL (Structured Query Language) Database on the second Subnet \u2014 structured data storage for your application.\n2. Place a Blob Storage block on the second Subnet \u2014 file storage for images, documents, and backups.',
      hints: [
        'Keeping data resources on a dedicated Subnet isolates them from the application tier.',
        'You need at least two data blocks to complete this step.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'data', onContainerLayer: 'subnet' },
        { type: 'min-block-count', category: 'data', count: 2 },
      ],
      checkpoint: dataStorageCheckpointAppTier,
    },
    {
      id: 'step-data-storage-wire-flow',
      order: 5,
      title: 'Wire the Data Flow',
      instruction:
        '1. Draw a connection from Internet to Application Gateway.\n2. Draw a connection from Application Gateway to Virtual Machine.\n3. Draw a connection from Virtual Machine to SQL Database.\n4. Draw a connection from Virtual Machine to Blob Storage.',
      hints: [
        'Start with the external path: Internet → Gateway → Virtual Machine. Then connect the Virtual Machine to both data services.',
        'Switch to Connect mode, then click source followed by target for each connection.',
        '🎉 Congratulations! You built a data-tier architecture with proper network isolation. Next, try the Event-Driven Data Pipeline scenario to learn asynchronous processing!',
      ],
      validationRules: [
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: dataStorageCheckpointFull,
    },
  ],
};

const fullStackInitialArchitecture: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [],
  connections: [],
  externalActors: [],
};

const fullStackCheckpointFoundation: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnfs-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
  ],
  connections: [],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const fullStackCheckpointWebData: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnfs-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scnfs-subnet1',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scnfs-subnet1',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scnfs-db',
      name: 'Azure Database for PostgreSQL',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'sql-database',
      category: 'data',
      provider: 'azure',
      subtype: 'sql-database',
      parentId: 'container-scnfs-subnet2',
      position: { x: 1.8, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-storage',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      provider: 'azure',
      subtype: 'blob-storage',
      parentId: 'container-scnfs-subnet2',
      position: { x: 4.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
  ],
  connections: [
    {
      id: 'conn-scnfs-internet-gw',
      from: endpointId('ext-internet', 'output', 'data'),
      to: endpointId('block-scnfs-gw', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-gw-vm',
      from: endpointId('block-scnfs-gw', 'output', 'data'),
      to: endpointId('block-scnfs-vm', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-db',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-db', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-storage',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-storage', 'input', 'data'),
      metadata: {},
    },
  ],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const fullStackCheckpointWithServerless: ArchitectureSnapshot = {
  name: 'Full-Stack Event Processing Learning Scenario',
  version: '1',
  endpoints: [],
  nodes: [
    {
      id: 'container-scnfs-vnet',
      name: 'VNet',
      kind: 'container',
      layer: 'region',
      resourceType: CONTAINER_RESOURCE_TYPE.region,
      category: 'network',
      provider: 'azure',
      parentId: null,
      position: { x: 0, y: 0, z: 0 },
      frame: { width: 12, height: 0.3, depth: 10 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet1',
      name: 'Subnet 1',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'container-scnfs-subnet2',
      name: 'Subnet 2',
      kind: 'container',
      layer: 'subnet',
      resourceType: CONTAINER_RESOURCE_TYPE.subnet,
      category: 'network',
      provider: 'azure',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.3, z: 0 },
      frame: { width: 5, height: 0.2, depth: 8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-gw',
      name: 'Azure Application Gateway',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'application-gateway',
      category: 'delivery',
      provider: 'azure',
      subtype: 'application-gateway',
      parentId: 'container-scnfs-subnet1',
      position: { x: -4.2, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-vm',
      name: 'Azure VM',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'vm',
      category: 'compute',
      provider: 'azure',
      subtype: 'vm',
      parentId: 'container-scnfs-subnet1',
      position: { x: -1.8, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scnfs-db',
      name: 'Azure Database for PostgreSQL',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'sql-database',
      category: 'data',
      provider: 'azure',
      subtype: 'sql-database',
      parentId: 'container-scnfs-subnet2',
      position: { x: 1.8, y: 0.5, z: -1.8 },
      metadata: {},
    },
    {
      id: 'block-scnfs-storage',
      name: 'Azure Blob Storage',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'blob-storage',
      category: 'data',
      provider: 'azure',
      subtype: 'blob-storage',
      parentId: 'container-scnfs-subnet2',
      position: { x: 4.2, y: 0.5, z: 1.2 },
      metadata: {},
    },
    {
      id: 'block-scnfs-api',
      name: 'Azure Functions',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      provider: 'azure',
      subtype: 'functions',
      parentId: 'container-scnfs-vnet',
      position: { x: -4, y: 0.5, z: 3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-worker',
      name: 'Azure Functions (Worker)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      provider: 'azure',
      subtype: 'functions',
      parentId: 'container-scnfs-vnet',
      position: { x: 0, y: 0.5, z: 3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-batch',
      name: 'Azure Functions (Batch)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'functions',
      category: 'compute',
      provider: 'azure',
      subtype: 'functions',
      parentId: 'container-scnfs-vnet',
      position: { x: 4, y: 0.5, z: 3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-queue',
      name: 'Azure Service Bus',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'service-bus',
      category: 'messaging',
      provider: 'azure',
      subtype: 'service-bus',
      parentId: 'container-scnfs-vnet',
      position: { x: -3, y: 0.5, z: -3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-event',
      name: 'Azure Event Grid',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'messaging',
      provider: 'azure',
      subtype: 'event-grid',
      parentId: 'container-scnfs-vnet',
      position: { x: 0, y: 0.5, z: -3 },
      metadata: {},
    },
    {
      id: 'block-scnfs-timer',
      name: 'Azure Event Grid (Timer)',
      kind: 'resource',
      layer: 'resource',
      resourceType: 'event-grid',
      category: 'operations',
      provider: 'azure',
      subtype: 'event-grid',
      parentId: 'container-scnfs-vnet',
      position: { x: 3, y: 0.5, z: -3 },
      metadata: {},
    },
  ],
  connections: [
    {
      id: 'conn-scnfs-internet-gw',
      from: endpointId('ext-internet', 'output', 'data'),
      to: endpointId('block-scnfs-gw', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-gw-vm',
      from: endpointId('block-scnfs-gw', 'output', 'data'),
      to: endpointId('block-scnfs-vm', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-db',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-db', 'input', 'data'),
      metadata: {},
    },
    {
      id: 'conn-scnfs-vm-storage',
      from: endpointId('block-scnfs-vm', 'output', 'data'),
      to: endpointId('block-scnfs-storage', 'input', 'data'),
      metadata: {},
    },
  ],
  externalActors: [
    { id: 'ext-internet', name: 'Internet', type: 'internet', position: { x: -3, y: 0, z: -3 } },
  ],
};

const fullStackScenario: Scenario = {
  id: 'scenario-full-stack',
  name: 'Full-Stack Web App with Event Processing',
  description:
    'Build the most complete architecture — a web application with a database, file storage, and an event-driven serverless layer that processes data automatically.',
  difficulty: 'advanced',
  category: 'serverless',
  tags: ['full-stack', 'serverless', 'event-driven', 'advanced'],
  estimatedMinutes: 15,
  initialArchitecture: fullStackInitialArchitecture,
  steps: [
    {
      id: 'step-full-stack-foundation',
      order: 1,
      title: 'Build the Network Foundation',
      instruction:
        '1. Create a Network container — your private cloud network.\n2. Add Subnet 1 inside the Network — for your web tier (gateway + server).\n3. Add Subnet 2 inside the Network — for data services (database + storage).',
      hints: [
        'Start by creating the Network container (VNet), then add two Subnets inside it.',
        'Separating web and data resources onto different Subnets improves security and organization.',
      ],
      validationRules: [
        { type: 'container-exists', containerLayer: 'region' },
        { type: 'min-container-count', containerLayer: 'subnet', count: 2 },
      ],
    },
    {
      id: 'step-full-stack-web-tier',
      order: 2,
      title: 'Deploy the Web Tier',
      instruction:
        '1. Place an Application Gateway on Subnet 1 — the entry point that receives internet traffic.\n2. Place a Virtual Machine (a cloud computer that runs your app) on Subnet 1.\n3. Draw a connection from Internet to Application Gateway.\n4. Draw a connection from Application Gateway to Virtual Machine.',
      hints: [
        'The Application Gateway receives internet traffic. The Virtual Machine runs your web application. Both belong on Subnet 1.',
        'Finish the web tier first before adding data or serverless components.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'delivery', onContainerLayer: 'subnet' },
        { type: 'block-exists', category: 'compute', onContainerLayer: 'subnet' },
        { type: 'connection-exists', sourceCategory: 'internet', targetCategory: 'delivery' },
        { type: 'connection-exists', sourceCategory: 'delivery', targetCategory: 'compute' },
      ],
      checkpoint: fullStackCheckpointFoundation,
    },
    {
      id: 'step-full-stack-data-services',
      order: 3,
      title: 'Add Data Services',
      instruction:
        '1. Place a PostgreSQL Database (a managed database for structured data) on Subnet 2.\n2. Place a Blob Storage block (cloud file storage for images, documents, and backups) on Subnet 2.\n3. Draw a connection from Virtual Machine to PostgreSQL Database.\n4. Draw a connection from Virtual Machine to Blob Storage.',
      hints: [
        'Keeping data services on a separate Subnet isolates them from direct internet access.',
        'You need at least one compute-to-data connection for validation to pass.',
      ],
      validationRules: [
        { type: 'block-exists', category: 'data', onContainerLayer: 'subnet' },
        { type: 'min-block-count', category: 'data', count: 2 },
        { type: 'connection-exists', sourceCategory: 'compute', targetCategory: 'data' },
      ],
      checkpoint: fullStackCheckpointWebData,
    },
    {
      id: 'step-full-stack-serverless-layer',
      order: 4,
      title: 'Build the Serverless Layer',
      instruction:
        'Add the serverless event processing layer on the Network container:\n1. Place 3 Azure Functions blocks (API, Worker, Batch) — small pieces of code that run automatically when triggered.\n2. Place a Service Bus (a message queue that buffers work items).\n3. Place an Event Grid (event notifications).\n4. Place a Timer Trigger (a scheduled task that runs at set intervals).\n5. Draw a connection from Service Bus to Worker Function.\n6. Draw a connection from Event Grid to Batch Function.\n7. Draw a connection from Timer Trigger to Batch Function.',
      hints: [
        'All serverless resources belong on the Network container, not inside a Subnet.',
        'Messaging resources (Service Bus, Event Grid, Timer) trigger Functions to process data automatically.',
      ],
      validationRules: [
        { type: 'min-block-count', category: 'compute', count: 4 },
        { type: 'block-exists', category: 'messaging', onContainerLayer: 'region' },
        { type: 'connection-exists', sourceCategory: 'messaging', targetCategory: 'compute' },
      ],
      checkpoint: fullStackCheckpointWithServerless,
    },
    {
      id: 'step-full-stack-final-validation',
      order: 5,
      title: 'Validate Your Architecture',
      instruction:
        'Validate your complete architecture. Open the Validation panel and fix any remaining issues.',
      hints: [
        'Check that all blocks are in the correct containers and all connections follow allowed patterns.',
        'You should have at least 4 compute blocks (1 Virtual Machine + 3 Functions) and 2 Subnets.',
        '🎉 Congratulations! You built a full-stack architecture with web, data, and serverless event processing. You are ready to design real cloud architectures!',
      ],
      validationRules: [
        { type: 'architecture-valid' },
        { type: 'min-block-count', category: 'compute', count: 4 },
        { type: 'min-container-count', containerLayer: 'subnet', count: 2 },
      ],
    },
  ],
};

export function registerBuiltinScenarios(): void {
  registerScenario(threeTierScenario);
  registerScenario(serverlessApiScenario);
  registerScenario(eventPipelineScenario);
  registerScenario(simpleComputeScenario);
  registerScenario(dataStorageScenario);
  registerScenario(fullStackScenario);
}
